const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const tools=[];const add=(cat,id,icon,title,desc,render)=>tools.push({cat,id,icon,title,desc,render});
const cats=['Image','Video','Audio','Text','Calculator','Security','Data','Design','Developer','Study','Games'];
const dl=(blob,name)=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function filePick(accept,multiple=false){return new Promise(r=>{const i=document.createElement('input');i.type='file';i.accept=accept;i.multiple=multiple;i.onchange=()=>r(multiple?[...i.files]:i.files[0]);i.click()})}
function imageLoad(file){return new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src=URL.createObjectURL(file)})}
function canvasBlob(c,type='image/png',q=.9){return new Promise(r=>c.toBlob(r,type,q))}
function basicFileUI(accept,cb,multiple=false){const d=document.createElement('div');d.className='drop';d.innerHTML=`<b>Choose file${multiple?'s':''}</b><br><small>Processing stays in this browser.</small><div class="actions"><button class="btn">Select</button></div>`;d.querySelector('button').onclick=async()=>cb(await filePick(accept,multiple));return d}
function fields(html){const d=document.createElement('div');d.innerHTML=html;return d}
// IMAGE
add('Image','resize','🖼️','Image Resize','Resize any image locally.',b=>{const d=basicFileUI('image/*',async f=>{const im=await imageLoad(f), box=fields(`<div class="grid2"><label>Width<input id=w type=number value=${im.naturalWidth}></label><label>Height<input id=h type=number value=${im.naturalHeight}></label></div><div class=actions><button class=btn id=go>Resize & Download</button></div>`);d.replaceChildren(im);d.after(box);box.querySelector('#go').onclick=async()=>{const c=document.createElement('canvas');c.width=+box.querySelector('#w').value;c.height=+box.querySelector('#h').value;c.getContext('2d').drawImage(im,0,0,c.width,c.height);dl(await canvasBlob(c,'image/png'),f.name.replace(/\.[^.]+$/,'')+'-resized.png')};});return d});
add('Image','compress','📦','Image Compress','Reduce JPG/WebP/PNG output size.',b=>basicFileUI('image/*',async f=>{const im=await imageLoad(f);const d=fields(`<label>Quality <input id=q type=range min=.1 max=1 step=.05 value=.75></label><div class=actions><button class=btn id=go>Compress & Download</button></div>`);d.querySelector('#go').onclick=async()=>{const c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;c.getContext('2d').drawImage(im,0,0);dl(await canvasBlob(c,'image/jpeg',+d.querySelector('#q').value),f.name.replace(/\.[^.]+$/,'')+'-compressed.jpg')};document.querySelector('.drop')?.after(d)}));
add('Image','convert','🔁','Image Converter','Convert images to PNG, JPG or WebP.',b=>basicFileUI('image/*',async f=>{const im=await imageLoad(f),d=fields(`<select id=t><option value=image/png>PNG</option><option value=image/jpeg>JPG</option><option value=image/webp>WebP</option></select><div class=actions><button class=btn id=go>Convert</button></div>`);d.querySelector('#go').onclick=async()=>{const t=d.querySelector('#t').value,c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;c.getContext('2d').drawImage(im,0,0);const ext=t.split('/')[1].replace('jpeg','jpg');dl(await canvasBlob(c,t,.92),f.name.replace(/\.[^.]+$/,'')+'.'+ext)};document.querySelector('.drop')?.after(d)}));
add('Image','crop','✂️','Image Crop','Crop using X/Y/width/height.',b=>basicFileUI('image/*',async f=>{const im=await imageLoad(f),d=fields(`<div class=grid2><input id=x type=number value=0 placeholder=X><input id=y type=number value=0 placeholder=Y><input id=w type=number value=${im.naturalWidth} placeholder=Width><input id=h type=number value=${im.naturalHeight} placeholder=Height></div><div class=actions><button class=btn id=go>Crop & Download</button></div>`);d.querySelector('#go').onclick=async()=>{const c=document.createElement('canvas');c.width=+d.querySelector('#w').value;c.height=+d.querySelector('#h').value;c.getContext('2d').drawImage(im,+d.querySelector('#x').value,+d.querySelector('#y').value,c.width,c.height,0,0,c.width,c.height);dl(await canvasBlob(c,'image/png'),'cropped.png')};document.querySelector('.drop')?.after(d)}));
add('Image','strip','🧽','Remove Image Metadata','Re-encode an image to strip common embedded metadata.',b=>basicFileUI('image/*',async f=>{const im=await imageLoad(f),c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;c.getContext('2d').drawImage(im,0,0);dl(await canvasBlob(c,'image/png'),'metadata-stripped.png')}));
// VIDEO
add('Video','trim','🎬','Video Trim','Trim a video and export a browser-recorded WebM.',b=>basicFileUI('video/*',async f=>{const v=document.createElement('video');v.controls=true;v.className='preview';v.src=URL.createObjectURL(f);const d=fields(`<div class=grid2><label>Start sec<input id=s type=number min=0 step=.1 value=0></label><label>End sec<input id=e type=number min=0 step=.1 value=5></label></div><div class=actions><button class=btn id=go>Trim to WebM</button></div>`);document.querySelector('.drop')?.append(v,d);v.onloadedmetadata=()=>d.querySelector('#e').value=Math.min(5,v.duration);d.querySelector('#go').onclick=()=>recordVideo(v,+d.querySelector('#s').value,+d.querySelector('#e').value,.8)}));
async function recordVideo(v,start,end,scale){if(!window.MediaRecorder)return alert('MediaRecorder is not supported here.');const c=document.createElement('canvas');c.width=(v.videoWidth||640)*scale;c.height=(v.videoHeight||360)*scale;const ctx=c.getContext('2d');const stream=c.captureStream(30),rec=new MediaRecorder(stream,{mimeType:'video/webm'}),chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>dl(new Blob(chunks,{type:'video/webm'}),'trimmed.webm');v.currentTime=start;await v.play();rec.start();const loop=()=>{if(v.currentTime>=end){rec.stop();v.pause();return}ctx.drawImage(v,0,0,c.width,c.height);requestAnimationFrame(loop)};loop()}
add('Video','convert','🔄','Video Convert','Convert browser-playable video to WebM locally.',b=>basicFileUI('video/*',async f=>{const v=document.createElement('video');v.src=URL.createObjectURL(f);v.controls=true;v.className='preview';document.querySelector('.drop')?.append(v);const d=fields(`<div class=actions><button class=btn id=go>Record as WebM</button></div>`);document.querySelector('.drop')?.after(d);d.querySelector('#go').onclick=()=>recordVideo(v,0,v.duration,1)}));
add('Video','compress','📦','Video Compression','Re-record at a smaller canvas size/bitrate as WebM.',b=>basicFileUI('video/*',async f=>{const v=document.createElement('video');v.src=URL.createObjectURL(f);v.controls=true;v.className='preview';document.querySelector('.drop')?.append(v);const d=fields(`<label>Scale <select id=sc><option value=.5>50%</option><option value=.7>70%</option><option value=.8>80%</option></select></label><div class=actions><button class=btn id=go>Compress</button></div>`);document.querySelector('.drop')?.after(d);d.querySelector('#go').onclick=()=>recordVideo(v,0,v.duration,+d.querySelector('#sc').value)}));
add('Video','gif','🌀','Video to GIF','Create a short animated GIF in the browser when gif.js is available.',b=>basicFileUI('video/*',async f=>{if(!window.GIF)return alert('GIF encoder could not load. Check internet connection.');const v=document.createElement('video');v.src=URL.createObjectURL(f);v.muted=true;document.querySelector('.drop')?.append(v);const d=fields(`<div class=grid2><input id=s type=number value=0 min=0 step=.1><input id=e type=number value=3 min=.2 step=.1></div><div class=actions><button class=btn id=go>Create GIF</button></div>`);document.querySelector('.drop')?.after(d);d.querySelector('#go').onclick=async()=>{const c=document.createElement('canvas');c.width=320;c.height=Math.round(320*(v.videoHeight/v.videoWidth||.56));const g=new GIF({workers:2,quality:10,width:c.width,height:c.height,workerScript:'https://cdn.jsdelivr.net/npm/gif.js@0.2.0/dist/gif.worker.js'});v.currentTime=+d.querySelector('#s').value;await v.play();const end=+d.querySelector('#e').value;await new Promise(done=>{const tick=()=>{if(v.currentTime>=end){v.pause();done();return}c.getContext('2d').drawImage(v,0,0,c.width,c.height);g.addFrame(c,{copy:true,delay:100});setTimeout(tick,100)};tick()});g.on('finished',blob=>dl(blob,'video.gif'));g.render()}}));
// AUDIO
async function decodeAudio(f){return await new AudioContext().decodeAudioData(await f.arrayBuffer())}
function audioWav(buf,start=0,end=buf.duration,gain=1){const rate=buf.sampleRate,ch=buf.numberOfChannels,s=Math.floor(start*rate),e=Math.floor(end*rate),frames=e-s,out=new ArrayBuffer(44+frames*ch*2),v=new DataView(out);const ws=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))};ws(0,'RIFF');v.setUint32(4,36+frames*ch*2,true);ws(8,'WAVE');ws(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,ch,true);v.setUint32(24,rate,true);v.setUint32(28,rate*ch*2,true);v.setUint16(32,ch*2,true);v.setUint16(34,16,true);ws(36,'data');v.setUint32(40,frames*ch*2,true);let p=44;for(let i=0;i<frames;i++)for(let c=0;c<ch;c++){let x=Math.max(-1,Math.min(1,buf.getChannelData(c)[s+i]*gain));v.setInt16(p,x<0?x*32768:x*32767,true);p+=2}return new Blob([out],{type:'audio/wav'})}
add('Audio','trim','✂️','Audio Trim','Trim audio and export WAV.',b=>basicFileUI('audio/*',async f=>{const a=await decodeAudio(f),d=fields(`<div class=grid2><label>Start<input id=s type=number value=0 step=.1></label><label>End<input id=e type=number value=${a.duration.toFixed(1)} step=.1></label></div><button class=btn id=go>Trim & Download</button>`);document.querySelector('.drop')?.after(d);d.querySelector('#go').onclick=()=>dl(audioWav(a,+d.querySelector('#s').value,+d.querySelector('#e').value),'trimmed.wav')}));
add('Audio','volume','🔊','Audio Volume','Adjust gain and export WAV.',b=>basicFileUI('audio/*',async f=>{const a=await decodeAudio(f),d=fields(`<label>Volume <input id=g type=range min=0 max=2 step=.05 value=1></label><button class=btn id=go>Export WAV</button>`);document.querySelector('.drop')?.after(d);d.querySelector('#go').onclick=()=>dl(audioWav(a,0,a.duration,+d.querySelector('#g').value),'volume-adjusted.wav')}));
add('Audio','convert','🔄','Audio Converter','Convert browser-decodable audio to WAV.',b=>basicFileUI('audio/*',async f=>{const a=await decodeAudio(f);dl(audioWav(a),'converted.wav')}));
// TEXT
add('Text','counter','📝','Word Counter','Count words, characters, lines and paragraphs.',b=>{const d=fields(`<textarea id=t rows=14 placeholder="Type or paste text…"></textarea><div id=o class=out></div>`);d.querySelector('#t').oninput=()=>{const x=d.querySelector('#t').value;d.querySelector('#o').textContent=`Words: ${x.trim()?x.trim().split(/\s+/).length:0}\nCharacters: ${x.length}\nCharacters without spaces: ${x.replace(/\s/g,'').length}\nLines: ${x?x.split(/\n/).length:0}\nParagraphs: ${x.trim()?x.trim().split(/\n\s*\n/).length:0}`};return d});
add('Text','case','🔤','Case Converter','UPPERCASE, lowercase, Title Case and sentence case.',b=>{const d=fields(`<textarea id=t rows=12></textarea><div class=actions><button class=btn data-x=upper>UPPER</button><button class=btn data-x=lower>lower</button><button class=btn data-x=title>Title</button><button class=btn data-x=sentence>Sentence</button></div>`);d.querySelectorAll('button').forEach(x=>x.onclick=()=>{let s=d.querySelector('#t');if(x.dataset.x==='upper')s.value=s.value.toUpperCase();if(x.dataset.x==='lower')s.value=s.value.toLowerCase();if(x.dataset.x==='title')s.value=s.value.toLowerCase().replace(/\b\w/g,m=>m.toUpperCase());if(x.dataset.x==='sentence')s.value=s.value.toLowerCase().replace(/(^|[.!?]\s+)\w/g,m=>m.toUpperCase())});return d});
add('Text','json','{}','JSON Formatter','Format, validate and minify JSON.',b=>{const d=fields(`<textarea id=t rows=14 placeholder='{"name":"Faraz"}'></textarea><div class=actions><button class=btn id=f>Format</button><button class="btn secondary" id=m>Minify</button></div><div id=o class=out></div>`);d.querySelector('#f').onclick=()=>jsonAct(2);d.querySelector('#m').onclick=()=>jsonAct(0);function jsonAct(sp){try{d.querySelector('#o').textContent=JSON.stringify(JSON.parse(d.querySelector('#t').value),null,sp)}catch(e){d.querySelector('#o').textContent='Invalid JSON: '+e.message}}return d});
// CALCULATOR
add('Calculator','scientific','🧮','Scientific Calculator','Evaluate common math expressions locally.',b=>{const d=fields(`<input id=x placeholder="Example: sin(pi/2)+sqrt(25)*3"><div class=actions><button class=btn id=go>Calculate</button></div><div id=o class="out big"></div>`);d.querySelector('#go').onclick=()=>{try{const x=d.querySelector('#x').value.replace(/\^/g,'**').replace(/sin\(/g,'Math.sin(').replace(/cos\(/g,'Math.cos(').replace(/tan\(/g,'Math.tan(').replace(/sqrt\(/g,'Math.sqrt(').replace(/log\(/g,'Math.log10(').replace(/pi/gi,'Math.PI');d.querySelector('#o').textContent=Function('"use strict";return ('+x+')')()}catch(e){d.querySelector('#o').textContent='Invalid expression'}};return d});
add('Calculator','percentage','%','Percentage Calculator','Find percentage, increase/decrease and reverse percentage.',b=>{const d=fields(`<div class=grid2><input id=a type=number placeholder="Value"><input id=p type=number placeholder="Percent"></div><div class=actions><button class=btn id=go>Calculate</button></div><div id=o class=out></div>`);d.querySelector('#go').onclick=()=>{let a=+d.querySelector('#a').value,p=+d.querySelector('#p').value;d.querySelector('#o').textContent=`${p}% of ${a} = ${a*p/100}\nIncrease = ${a*(1+p/100)}\nDecrease = ${a*(1-p/100)}`};return d});
add('Calculator','emi','💰','EMI Calculator','Calculate monthly loan EMI.',b=>{const d=fields(`<div class=grid2><input id=p type=number placeholder="Principal"><input id=r type=number placeholder="Annual interest %"><input id=n type=number placeholder="Months"></div><button class=btn id=go>Calculate EMI</button><div id=o class=out></div>`);d.querySelector('#go').onclick=()=>{const p=+d.querySelector('#p').value,r=+d.querySelector('#r').value/1200,n=+d.querySelector('#n').value,m=r? p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):p/n;d.querySelector('#o').textContent=`Monthly EMI: ${m.toFixed(2)}\nTotal payment: ${(m*n).toFixed(2)}\nInterest: ${(m*n-p).toFixed(2)}`};return d});
add('Calculator','units','📏','Unit Converter','Length, weight and temperature conversions.',b=>{const d=fields(`<div class=grid2><input id=x type=number value=1><select id=f><option value=m>meter</option><option value=km>kilometer</option><option value=cm>centimeter</option><option value=ft>foot</option><option value=in>inch</option><option value=kg>kilogram</option><option value=lb>pound</option><option value=c>Celsius</option><option value=fah>Fahrenheit</option></select><select id=t><option value=m>meter</option><option value=km>kilometer</option><option value=cm>centimeter</option><option value=ft>foot</option><option value=in>inch</option><option value=kg>kilogram</option><option value=lb>pound</option><option value=c>Celsius</option><option value=fah>Fahrenheit</option></select></div><button class=btn id=go>Convert</button><div id=o class=out></div>`);d.querySelector('#go').onclick=()=>{let x=+d.querySelector('#x').value,f=d.querySelector('#f').value,t=d.querySelector('#t').value;const L={m:1,km:1000,cm:.01,ft:.3048,in:.0254},W={kg:1,lb:.453592};let y;if(f==='c'||f==='fah'){let c=f==='c'?x:(x-32)*5/9;y=t==='c'?c:c*9/5+32}else if(L[f]&&L[t])y=x*L[f]/L[t];else if(W[f]&&W[t])y=x*W[f]/W[t];else y='Incompatible units';d.querySelector('#o').textContent=y};return d});
// SECURITY
add('Security','password','🔐','Password Generator','Generate strong random passwords locally.',b=>{const d=fields(`<div class=grid2><input id=n type=number min=4 max=200 value=20><label><input id=s type=checkbox checked> Symbols</label></div><button class=btn id=go>Generate</button><input id=o readonly>`);d.querySelector('#go').onclick=()=>{const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789'+(d.querySelector('#s').checked?'!@#$%^&*_-+=?':'');let a=new Uint32Array(+d.querySelector('#n').value);crypto.getRandomValues(a);d.querySelector('#o').value=[...a].map(x=>chars[x%chars.length]).join('')};return d});
add('Security','hash','#','SHA-256 Hash','Hash text or a file with Web Crypto.',b=>{const d=fields(`<textarea id=t rows=7 placeholder="Text to hash"></textarea><button class=btn id=go>Hash Text</button><div id=o class=out></div>`);d.querySelector('#go').onclick=async()=>{const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(d.querySelector('#t').value));d.querySelector('#o').textContent=[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')};return d});
add('Security','encrypt','🔒','Local Text Encryption','Encrypt/decrypt text using AES-GCM; key never leaves this page.',b=>{const d=fields(`<textarea id=t rows=8 placeholder="Text"></textarea><input id=p type=password placeholder="Password"><div class=actions><button class=btn id=e>Encrypt</button><button class="btn secondary" id=x>Decrypt</button></div><textarea id=o rows=8 placeholder="Result"></textarea>`);const key=async p=>crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',new TextEncoder().encode(p)),{name:'AES-GCM'},false,['encrypt','decrypt']);d.querySelector('#e').onclick=async()=>{try{const iv=crypto.getRandomValues(new Uint8Array(12)),k=await key(d.querySelector('#p').value),ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},k,new TextEncoder().encode(d.querySelector('#t').value)));d.querySelector('#o').value=btoa(String.fromCharCode(...iv,...ct))}catch(e){alert(e.message)}};d.querySelector('#x').onclick=async()=>{try{const raw=Uint8Array.from(atob(d.querySelector('#t').value),c=>c.charCodeAt(0)),k=await key(d.querySelector('#p').value),pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:raw.slice(0,12)},k,raw.slice(12));d.querySelector('#o').value=new TextDecoder().decode(pt)}catch(e){alert('Wrong password or invalid data')}};return d});
// DATA
function csvParse(s){return s.trim().split(/\r?\n/).map(r=>r.split(/,(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)/).map(x=>x.replace(/^\"|\"$/g,'')))}function csvString(rows){return rows.map(r=>r.map(x=>'"'+String(x).replace(/"/g,'""')+'"').join(',')).join('\n')}
add('Data','csv','📊','CSV Viewer & Editor','Paste CSV, edit cells, and download it.',b=>{const d=fields(`<textarea id=t rows=10 placeholder="name,score\nFaraz,100"></textarea><div class=actions><button class=btn id=load>Load Table</button><button class="btn secondary" id=save>Download CSV</button></div><div id=o></div>`);let rows=[];d.querySelector('#load').onclick=()=>{rows=csvParse(d.querySelector('#t').value);render()};
// ================= EXTRA BROWSER-ONLY TOOLS =================
const blobFromText=(text,type='text/plain')=>new Blob([text],{type});
const downloadText=(text,name,type='text/plain')=>dl(blobFromText(text,type),name);
const wrapTool=(html,fn)=>{const d=fields(html);fn(d);return d};
const readText=f=>f.text();
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));

// More Image tools
add('Image','filters','🎛️','Image Filters','Brightness, contrast, saturation, grayscale and blur.',b=>basicFileUI('image/*',async f=>{const im=await imageLoad(f),d=fields(`<div class="grid2"><label>Brightness<input id="br" type="range" min="0" max="2" step=".05" value="1"></label><label>Contrast<input id="co" type="range" min="0" max="2" step=".05" value="1"></label><label>Saturation<input id="sa" type="range" min="0" max="2" step=".05" value="1"></label><label>Blur<input id="bl" type="range" min="0" max="12" step="1" value="0"></label></div><div class="actions"><button class="btn" id="go">Apply & Download</button></div>`);document.querySelector('.drop')?.after(d);d.querySelector('#go').onclick=async()=>{const c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;const x=c.getContext('2d');x.filter=`brightness(${d.querySelector('#br').value}) contrast(${d.querySelector('#co').value}) saturate(${d.querySelector('#sa').value}) blur(${d.querySelector('#bl').value}px)`;x.drawImage(im,0,0);dl(await canvasBlob(c,'image/png'),'filtered.png')}}));
add('Image','pixelate','🔲','Pixelate Image','Create a pixelated privacy effect.',b=>basicFileUI('image/*',async f=>{const im=await imageLoad(f),d=fields(`<label>Pixel size<input id="n" type="number" min="2" max="100" value="12"></label><button class="btn" id="go">Pixelate</button>`);document.querySelector('.drop')?.after(d);d.querySelector('#go').onclick=async()=>{const n=+d.querySelector('#n').value,c=document.createElement('canvas'),x=c.getContext('2d');c.width=im.naturalWidth;c.height=im.naturalHeight;const sw=Math.max(1,Math.floor(c.width/n)),sh=Math.max(1,Math.floor(c.height/n));const s=document.createElement('canvas');s.width=sw;s.height=sh;s.getContext('2d').drawImage(im,0,0,sw,sh);x.imageSmoothingEnabled=false;x.drawImage(s,0,0,c.width,c.height);dl(await canvasBlob(c,'image/png'),'pixelated.png')}}));
add('Image','contact','🧩','Contact Sheet','Combine multiple images into one contact sheet.',b=>basicFileUI('image/*',async fs=>{if(!fs?.length)return;const ims=await Promise.all(fs.map(imageLoad)),cols=3,cell=220,rows=Math.ceil(ims.length/cols),c=document.createElement('canvas');c.width=cols*cell;c.height=rows*cell;const x=c.getContext('2d');ims.forEach((im,i)=>{const cx=(i%cols)*cell,cy=Math.floor(i/cols)*cell,sc=Math.min(cell/im.naturalWidth,cell/im.naturalHeight);x.drawImage(im,cx+(cell-im.naturalWidth*sc)/2,cy+(cell-im.naturalHeight*sc)/2,im.naturalWidth*sc,im.naturalHeight*sc)});dl(await canvasBlob(c,'image/png'),'contact-sheet.png')},true));
add('Image','favicon','🌐','Favicon Generator','Create a 64×64 PNG favicon from an image.',b=>basicFileUI('image/*',async f=>{const im=await imageLoad(f),c=document.createElement('canvas');c.width=c.height=64;c.getContext('2d').drawImage(im,0,0,64,64);dl(await canvasBlob(c,'image/png'),'favicon.png')}));
add('Image','social','📐','Social Image Resizer','Resize an image to common social-media canvas sizes.',b=>basicFileUI('image/*',async f=>{const im=await imageLoad(f),d=fields(`<select id="p"><option value="1080x1080">Square 1080×1080</option><option value="1080x1920">Story/Short 1080×1920</option><option value="1280x720">Video 1280×720</option><option value="1200x630">Link/OG 1200×630</option></select><button class="btn" id="go">Resize</button>`);document.querySelector('.drop')?.after(d);d.querySelector('#go').onclick=async()=>{const [w,h]=d.querySelector('#p').value.split('x').map(Number),c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,w,h);const sc=Math.min(w/im.naturalWidth,h/im.naturalHeight);x.drawImage(im,(w-im.naturalWidth*sc)/2,(h-im.naturalHeight*sc)/2,im.naturalWidth*sc,im.naturalHeight*sc);dl(await canvasBlob(c,'image/png'),'social-'+w+'x'+h+'.png')}}));
add('Image','palette','🎨','Color Palette Extractor','Extract a simple dominant color palette from an image.',b=>basicFileUI('image/*',async f=>{const im=await imageLoad(f),c=document.createElement('canvas');c.width=50;c.height=50;c.getContext('2d').drawImage(im,0,0,50,50);const data=c.getContext('2d').getImageData(0,0,50,50).data, buckets={};for(let i=0;i<data.length;i+=16){const r=Math.round(data[i]/32)*32,g=Math.round(data[i+1]/32)*32,bl=Math.round(data[i+2]/32)*32,k=`${clamp(r,0,255)},${clamp(g,0,255)},${clamp(bl,0,255)}`;buckets[k]=(buckets[k]||0)+1}const top=Object.entries(buckets).sort((a,b)=>b[1]-a[1]).slice(0,8).map(x=>'#'+x[0].split(',').map(v=>Number(v).toString(16).padStart(2,'0')).join(''));b.innerHTML=`<div class="out">${top.map(x=>`<div style="display:inline-block;margin:5px;padding:12px;border-radius:8px;background:${x};color:${parseInt(x.slice(1),16)>0xffffff/2?'#000':'#fff'}">${x}</div>`).join('')}</div>`}));
add('Image','ascii','🔤','Image to ASCII','Convert an image into text art.',b=>basicFileUI('image/*',async f=>{const im=await imageLoad(f),c=document.createElement('canvas'),w=80,h=Math.max(1,Math.round(80*im.naturalHeight/im.naturalWidth*.5));c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);const d=c.getContext('2d').getImageData(0,0,w,h).data,ch='@%#*+=-:. ';let out='';for(let y=0;y<h;y++){for(let x=0;x<w;x++){const i=(y*w+x)*4,g=.299*d[i]+.587*d[i+1]+.114*d[i+2];out+=ch[Math.floor(g/256*ch.length)]}out+='\n'}const o=fields(`<pre class="out"></pre><button class="btn" id="dl">Download TXT</button>`);o.querySelector('pre').textContent=out;o.querySelector('#dl').onclick=()=>downloadText(out,'ascii.txt');document.querySelector('.drop')?.after(o)}));

// More Audio tools
function audioDecode(f){return f.arrayBuffer().then(buf=>new AudioContext().decodeAudioData(buf));}
add('Audio','speed','🐇','Audio Speed Changer','Change playback speed and export WAV.',b=>basicFileUI('audio/*',async f=>{const d=fields(`<label>Speed<input id="s" type="range" min=".5" max="2" step=".05" value="1"></label><button class="btn" id="go">Export WAV</button>`);document.querySelector('.drop')?.after(d);d.querySelector('#go').onclick=async()=>{const src=await audioDecode(f),rate=src.sampleRate,dur=src.duration/+d.querySelector('#s').value,off=new OfflineAudioContext(src.numberOfChannels,Math.ceil(dur*rate),rate),node=off.createBufferSource();node.buffer=src;node.playbackRate.value=+d.querySelector('#s').value;node.connect(off.destination);node.start();const out=await off.startRendering();dl(wavBlob(out),'audio-speed.wav')}}));
function wavBlob(buf){const ch=buf.numberOfChannels,rate=buf.sampleRate,len=buf.length*ch,ab=new ArrayBuffer(44+len*2),v=new DataView(ab),w=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))};w(0,'RIFF');v.setUint32(4,36+len*2,true);w(8,'WAVE');w(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,ch,true);v.setUint32(24,rate,true);v.setUint32(28,rate*ch*2,true);v.setUint16(32,ch*2,true);v.setUint16(34,16,true);w(36,'data');v.setUint32(40,len*2,true);let o=44;for(let i=0;i<buf.length;i++)for(let c=0;c<ch;c++){const s=clamp(buf.getChannelData(c)[i],-1,1);v.setInt16(o,s<0?s*0x8000:s*0x7fff,true);o+=2}return new Blob([v],{type:'audio/wav'})}
add('Audio','fade','🌅','Audio Fade In / Out','Apply fade-in and fade-out and export WAV.',b=>basicFileUI('audio/*',async f=>{const d=fields(`<div class="grid2"><label>Fade in sec<input id="i" type="number" min="0" value="1"></label><label>Fade out sec<input id="o" type="number" min="0" value="1"></label></div><button class="btn" id="go">Export WAV</button>`);document.querySelector('.drop')?.after(d);d.querySelector('#go').onclick=async()=>{const src=await audioDecode(f),off=new OfflineAudioContext(src.numberOfChannels,src.length,src.sampleRate),n=off.createBufferSource(),g=off.createGain();n.buffer=src;g.gain.setValueAtTime(0,0);g.gain.linearRampToValueAtTime(1,Math.min(+d.querySelector('#i').value,src.duration));const fo=Math.max(0,src.duration-+d.querySelector('#o').value);g.gain.setValueAtTime(1,fo);g.gain.linearRampToValueAtTime(0,src.duration);n.connect(g).connect(off.destination);n.start();dl(wavBlob(await off.startRendering()),'faded.wav')}}));
add('Audio','merge','🔗','Merge Audio Files','Join audio files sequentially and export WAV.',b=>basicFileUI('audio/*',async fs=>{const arr=await Promise.all(fs.map(audioDecode));const rate=arr[0].sampleRate,ch=Math.max(...arr.map(x=>x.numberOfChannels)),len=arr.reduce((n,x)=>n+x.length,0),off=new OfflineAudioContext(ch,len,rate);let t=0;arr.forEach(a=>{const n=off.createBufferSource();n.buffer=a;n.connect(off.destination);n.start(t/rate);t+=a.length});dl(wavBlob(await off.startRendering()),'merged.wav')},true));
add('Audio','recorder','🎙️','Audio Recorder','Record microphone audio locally as WebM/Opus.',b=>{const d=fields(`<button class="btn" id="s">Start</button><button class="btn secondary" id="x">Stop</button><div id="o" class="out"></div>`);let rec,ch=[];d.querySelector('#s').onclick=async()=>{const st=await navigator.mediaDevices.getUserMedia({audio:true});rec=new MediaRecorder(st);ch=[];rec.ondataavailable=e=>ch.push(e.data);rec.onstop=()=>{st.getTracks().forEach(t=>t.stop());const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(ch,{type:'audio/webm'}));a.download='recording.webm';a.textContent='Download recording';d.querySelector('#o').replaceChildren(a)};rec.start()};d.querySelector('#x').onclick=()=>rec?.stop();return d});

// More Text / Data / Developer
add('Text','duplicates','🧹','Remove Duplicate Lines','Remove repeated lines from text.',b=>{const d=fields(`<textarea id="i" rows="14"></textarea><button class="btn" id="go">Remove Duplicates</button><textarea id="o" rows="14"></textarea>`);d.querySelector('#go').onclick=()=>d.querySelector('#o').value=[...new Set(d.querySelector('#i').value.split(/\r?\n/))].join('\n');return d});
add('Text','sortlines','↕️','Sort Lines','Sort text lines alphabetically.',b=>{const d=fields(`<textarea id="i" rows="12"></textarea><button class="btn" id="go">Sort</button><textarea id="o" rows="12"></textarea>`);d.querySelector('#go').onclick=()=>d.querySelector('#o').value=d.querySelector('#i').value.split(/\r?\n/).sort((a,b)=>a.localeCompare(b)).join('\n');return d});
add('Text','slug','🔗','Slug Generator','Turn a title into a clean URL slug.',b=>{const d=fields(`<input id="i" placeholder="My Great Article"><button class="btn" id="go">Generate</button><input id="o" readonly>`);d.querySelector('#go').onclick=()=>d.querySelector('#o').value=d.querySelector('#i').value.toLowerCase().trim().replace(/[^\w\s-]/g,'').replace(/[\s_-]+/g,'-').replace(/^-+|-+$/g,'');return d});
add('Text','diff','🌓','Text Diff','Compare two text blocks and show changed lines.',b=>{const d=fields(`<textarea id="a" rows="10" placeholder="Original"></textarea><textarea id="b" rows="10" placeholder="New"></textarea><button class="btn" id="go">Compare</button><pre id="o" class="out"></pre>`);d.querySelector('#go').onclick=()=>{const a=d.querySelector('#a').value.split(/\r?\n/),bb=d.querySelector('#b').value.split(/\r?\n/),setA=new Set(a),setB=new Set(bb);d.querySelector('#o').textContent='Removed:\n'+a.filter(x=>!setB.has(x)).map(x=>'- '+x).join('\n')+'\n\nAdded:\n'+bb.filter(x=>!setA.has(x)).map(x=>'+ '+x).join('\n')};return d});
add('Text','url','🔗','URL Encoder / Decoder','Encode or decode URL text.',b=>{const d=fields(`<textarea id="i" rows="8"></textarea><button class="btn" id="e">Encode</button><button class="btn secondary" id="x">Decode</button><textarea id="o" rows="8"></textarea>`);d.querySelector('#e').onclick=()=>d.querySelector('#o').value=encodeURIComponent(d.querySelector('#i').value);d.querySelector('#x').onclick=()=>{try{d.querySelector('#o').value=decodeURIComponent(d.querySelector('#i').value)}catch(e){d.querySelector('#o').value='Invalid encoded URL'}};return d});
add('Text','entities','&lt;&gt;','HTML Entity Encoder','Encode or decode HTML entities.',b=>{const d=fields(`<textarea id="i" rows="8"></textarea><button class="btn" id="e">Encode</button><button class="btn secondary" id="x">Decode</button><textarea id="o" rows="8"></textarea>`);d.querySelector('#e').onclick=()=>d.querySelector('#o').value=d.querySelector('#i').value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');d.querySelector('#x').onclick=()=>{const t=document.createElement('textarea');t.innerHTML=d.querySelector('#i').value;d.querySelector('#o').value=t.value};return d});
add('Developer','jsonvalidate','✅','JSON Validator','Validate JSON and inspect its formatted structure.',b=>{const d=fields(`<textarea id="i" rows="14"></textarea><button class="btn" id="go">Validate</button><div id="o" class="out"></div>`);d.querySelector('#go').onclick=()=>{try{const x=JSON.parse(d.querySelector('#i').value);d.querySelector('#o').textContent='Valid JSON\n'+JSON.stringify(x,null,2)}catch(e){d.querySelector('#o').textContent='Invalid JSON: '+e.message}};return d});
add('Developer','jsonmin','🗜️','JSON Minifier','Minify JSON for compact output.',b=>{const d=fields(`<textarea id="i" rows="12"></textarea><button class="btn" id="go">Minify</button><textarea id="o" rows="12"></textarea>`);d.querySelector('#go').onclick=()=>{try{d.querySelector('#o').value=JSON.stringify(JSON.parse(d.querySelector('#i').value))}catch(e){d.querySelector('#o').value='Invalid JSON'}};return d});
add('Developer','jwt','🪪','JWT Decoder','Decode JWT header and payload locally; no verification.',b=>{const d=fields(`<textarea id="i" rows="5" placeholder="eyJ..."></textarea><button class="btn" id="go">Decode</button><pre id="o" class="out"></pre>`);d.querySelector('#go').onclick=()=>{try{const p=d.querySelector('#i').value.split('.');const dec=x=>JSON.parse(decodeURIComponent(escape(atob(x.replace(/-/g,'+').replace(/_/g,'/')))));d.querySelector('#o').textContent='Header:\n'+JSON.stringify(dec(p[0]),null,2)+'\n\nPayload:\n'+JSON.stringify(dec(p[1]),null,2)}catch(e){d.querySelector('#o').textContent='Invalid JWT format'}};return d});
add('Developer','timestamp','🕒','Unix Timestamp Converter','Convert Unix timestamps and dates.',b=>{const d=fields(`<input id="i" placeholder="e.g. 1791050000"><div class="actions"><button class="btn" id="a">Timestamp → Date</button><button class="btn secondary" id="b">Date → Timestamp</button></div><div id="o" class="out"></div>`);d.querySelector('#a').onclick=()=>{const n=Number(d.querySelector('#i').value);d.querySelector('#o').textContent=Number.isFinite(n)?new Date(n*1000).toISOString():'Invalid timestamp'};d.querySelector('#b').onclick=()=>{const x=new Date(d.querySelector('#i').value);d.querySelector('#o').textContent=isNaN(x)?'Invalid date':Math.floor(x.getTime()/1000)};return d});
add('Developer','sql','🗃️','SQL Formatter','Basic SQL readability formatter.',b=>{const d=fields(`<textarea id="i" rows="12"></textarea><button class="btn" id="go">Format SQL</button><textarea id="o" rows="12"></textarea>`);d.querySelector('#go').onclick=()=>{let s=d.querySelector('#i').value.replace(/\s+/g,' ').trim();['SELECT','FROM','WHERE','GROUP BY','ORDER BY','HAVING','LIMIT','VALUES','SET','JOIN','LEFT JOIN','RIGHT JOIN','INNER JOIN','UNION'].forEach(k=>s=s.replace(new RegExp('\\s+'+k+'\\s+','ig'),'\n'+k+' '));d.querySelector('#o').value=s};return d});
add('Developer','cssgradient','🌈','CSS Gradient Generator','Generate a CSS linear gradient.',b=>{const d=fields(`<div class="grid2"><input id="a" type="color" value="#6d5dfc"><input id="b" type="color" value="#00c2ff"></div><input id="d" type="number" value="90"><button class="btn" id="go">Generate</button><pre id="o" class="out"></pre>`);d.querySelector('#go').onclick=()=>d.querySelector('#o').textContent=`background: linear-gradient(${+d.querySelector('#d').value}deg, ${d.querySelector('#a').value}, ${d.querySelector('#b').value});`;return d});
add('Developer','shadow','◼️','CSS Box Shadow Generator','Generate a ready-to-copy box-shadow rule.',b=>{const d=fields(`<div class="grid2"><input id="x" type="number" value="4"><input id="y" type="number" value="8"><input id="b" type="number" value="20"><input id="s" type="number" value="0"></div><input id="c" type="color" value="#000000"><button class="btn" id="go">Generate</button><pre id="o" class="out"></pre>`);d.querySelector('#go').onclick=()=>d.querySelector('#o').textContent=`box-shadow: ${d.querySelector('#x').value}px ${d.querySelector('#y').value}px ${d.querySelector('#b').value}px ${d.querySelector('#s').value}px ${d.querySelector('#c').value};`;return d});
add('Developer','mime','📦','MIME Type Lookup','Look up common file MIME types.',b=>{const d=fields(`<input id="i" placeholder=".pdf or pdf"><button class="btn" id="go">Lookup</button><div id="o" class="out"></div>`);const m={pdf:'application/pdf',jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',gif:'image/gif',svg:'image/svg+xml',txt:'text/plain',html:'text/html',css:'text/css',js:'text/javascript',json:'application/json',csv:'text/csv',mp3:'audio/mpeg',wav:'audio/wav',mp4:'video/mp4',webm:'video/webm',zip:'application/zip'};d.querySelector('#go').onclick=()=>{let k=d.querySelector('#i').value.toLowerCase().replace(/^\./,'');d.querySelector('#o').textContent=m[k]||'MIME type not in local list'};return d});

// More Security
add('Security','uuid','🆔','UUID Generator','Generate random UUID v4 values locally.',b=>{const d=fields(`<input id="n" type="number" min="1" max="100" value="5"><button class="btn" id="go">Generate</button><textarea id="o" rows="10"></textarea>`);d.querySelector('#go').onclick=()=>{const n=clamp(+d.querySelector('#n').value,1,100);d.querySelector('#o').value=Array.from({length:n},()=>crypto.randomUUID()).join('\n')};return d});
add('Security','hashfile','#️⃣','File SHA-256 Hash','Calculate a file checksum locally.',b=>basicFileUI('*/*',async f=>{if(!f)return;const h=await crypto.subtle.digest('SHA-256',await f.arrayBuffer()),hex=[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('');const d=fields(`<div class="out">SHA-256<br><code>${hex}</code></div>`);document.querySelector('.drop')?.after(d)}));
add('Security','token','🎲','Random Token Generator','Generate cryptographically strong random tokens.',b=>{const d=fields(`<input id="n" type="number" min="8" max="256" value="32"><button class="btn" id="go">Generate</button><textarea id="o" rows="5"></textarea>`);d.querySelector('#go').onclick=()=>{const n=clamp(+d.querySelector('#n').value,8,256),a=new Uint8Array(n);crypto.getRandomValues(a);d.querySelector('#o').value=[...a].map(x=>x.toString(16).padStart(2,'0')).join('')};return d});
add('Security','totp','⏱️','TOTP Generator','Generate a one-time code from a Base32 secret locally.',b=>{const d=fields(`<input id="s" placeholder="BASE32 SECRET"><button class="btn" id="go">Generate</button><div id="o" class="big"></div><small>This is a local utility; check your account provider's setup rules.</small>`);d.querySelector('#go').onclick=async()=>{try{const sec=d.querySelector('#s').value.replace(/=+$/,'').toUpperCase();const alph='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits='';for(const ch of sec){const n=alph.indexOf(ch);if(n<0)throw Error('Invalid Base32');bits+=n.toString(2).padStart(5,'0')}const bytes=new Uint8Array(Math.floor(bits.length/8));for(let i=0;i<bytes.length;i++)bytes[i]=parseInt(bits.slice(i*8,i*8+8),2);const key=await crypto.subtle.importKey('raw',bytes,{name:'HMAC',hash:'SHA-1'},false,['sign']);const ctr=Math.floor(Date.now()/1000/30);const msg=new ArrayBuffer(8),v=new DataView(msg);v.setUint32(4,ctr);const sig=new Uint8Array(await crypto.subtle.sign('HMAC',key,msg));const off=sig[sig.length-1]&15;const code=((sig[off]&127)<<24|(sig[off+1]<<16)|(sig[off+2]<<8)|sig[off+3])%1000000;d.querySelector('#o').textContent=String(code).padStart(6,'0')}catch(e){d.querySelector('#o').textContent='Invalid secret'}};return d});

// More Calculators
const calc=(cat,id,icon,title,desc,html,fn)=>add(cat,id,icon,title,desc,b=>{const d=fields(html);d.querySelector('#go').onclick=()=>d.querySelector('#o').textContent=fn(d);return d});
calc('Calculator','discount','🏷️','Discount Calculator','Calculate sale price and savings.','<div class="grid2"><input id="p" type="number" placeholder="Price"><input id="r" type="number" placeholder="Discount %"></div><button class="btn" id="go">Calculate</button><div id="o" class="out"></div>',d=>{const p=+d.querySelector('#p').value,r=+d.querySelector('#r').value,s=p*r/100;return `Savings: ${s.toFixed(2)}\nFinal price: ${(p-s).toFixed(2)}`});
calc('Calculator','gst','🧾','GST Calculator','Calculate GST-inclusive or exclusive price.','<div class="grid2"><input id="p" type="number" placeholder="Amount"><input id="r" type="number" value="18" placeholder="GST %"></div><button class="btn" id="go">Calculate</button><div id="o" class="out"></div>',d=>{const p=+d.querySelector('#p').value,r=+d.querySelector('#r').value;return `GST: ${(p*r/100).toFixed(2)}\nTotal: ${(p*(1+r/100)).toFixed(2)}`});
calc('Calculator','profit','📈','Profit / Loss Calculator','Calculate profit, loss and percentage.','<div class="grid2"><input id="c" type="number" placeholder="Cost price"><input id="s" type="number" placeholder="Selling price"></div><button class="btn" id="go">Calculate</button><div id="o" class="out"></div>',d=>{const c=+d.querySelector('#c').value,s=+d.querySelector('#s').value,p=s-c;return `${p>=0?'Profit':'Loss'}: ${Math.abs(p).toFixed(2)}\nPercentage: ${(Math.abs(p)/c*100).toFixed(2)}%`});
calc('Calculator','age','🎂','Age Calculator','Calculate age from date of birth.','<input id="d" type="date"><button class="btn" id="go">Calculate</button><div id="o" class="out"></div>',d=>{const x=new Date(d.querySelector('#d').value),n=new Date();let y=n.getFullYear()-x.getFullYear();if(n<new Date(n.getFullYear(),x.getMonth(),x.getDate()))y--;return `${y} years old`});
calc('Calculator','datediff','📅','Date Difference','Calculate the number of days between two dates.','<div class="grid2"><input id="a" type="date"><input id="b" type="date"></div><button class="btn" id="go">Calculate</button><div id="o" class="out"></div>',d=>{const a=new Date(d.querySelector('#a').value),b=new Date(d.querySelector('#b').value);return `${Math.round(Math.abs(b-a)/86400000)} days`});
calc('Calculator','bmi','⚖️','BMI Calculator','Calculate BMI from height and weight.','<div class="grid2"><input id="w" type="number" placeholder="Weight kg"><input id="h" type="number" placeholder="Height cm"></div><button class="btn" id="go">Calculate</button><div id="o" class="out"></div>',d=>{const w=+d.querySelector('#w').value,h=+d.querySelector('#h').value/100;return `BMI: ${(w/(h*h)).toFixed(1)}`});
calc('Calculator','base','🔢','Number Base Converter','Convert decimal, binary and hexadecimal values.','<input id="i" placeholder="255"><select id="b"><option value="10">Decimal</option><option value="2">Binary</option><option value="16">Hexadecimal</option></select><button class="btn" id="go">Convert</button><div id="o" class="out"></div>',d=>{const n=parseInt(d.querySelector('#i').value,+d.querySelector('#b').value);return `Decimal: ${n}\nBinary: ${n.toString(2)}\nHex: ${n.toString(16).toUpperCase()}`});
calc('Calculator','ratio','➗','Ratio Calculator','Simplify a two-number ratio.','<div class="grid2"><input id="a" type="number"><input id="b" type="number"></div><button class="btn" id="go">Simplify</button><div id="o" class="out"></div>',d=>{let a=Math.abs(+d.querySelector('#a').value),b=Math.abs(+d.querySelector('#b').value);const g=(x,y)=>y?g(y,x%y):x;const z=g(a,b);return `${a/z}:${b/z}`});

// More Data
add('Data','csvjson','🔄','CSV ↔ JSON','Convert simple CSV data to JSON and back.',b=>{const d=fields(`<textarea id="i" rows="12" placeholder="name,age\nA,10"></textarea><div class="actions"><button class="btn" id="cj">CSV → JSON</button><button class="btn secondary" id="jc">JSON → CSV</button></div><textarea id="o" rows="12"></textarea>`);d.querySelector('#cj').onclick=()=>{const rows=d.querySelector('#i').value.trim().split(/\r?\n/).map(x=>x.split(',')),h=rows.shift();d.querySelector('#o').value=JSON.stringify(rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]??'']))),null,2)};d.querySelector('#jc').onclick=()=>{try{const a=JSON.parse(d.querySelector('#i').value),h=[...new Set(a.flatMap(x=>Object.keys(x)))];d.querySelector('#o').value=[h.join(','),...a.map(x=>h.map(k=>String(x[k]??'').replace(/,/g,' ')).join(','))].join('\n')}catch(e){d.querySelector('#o').value='Invalid JSON'}};return d});
add('Data','randomdata','🎲','Random Data Generator','Generate sample names, numbers and emails for testing.',b=>{const d=fields(`<input id="n" type="number" min="1" max="500" value="20"><button class="btn" id="go">Generate CSV</button><textarea id="o" rows="14"></textarea>`);d.querySelector('#go').onclick=()=>{const n=clamp(+d.querySelector('#n').value,1,500),names=['Aman','Riya','Kabir','Neha','Arjun','Sara'];let s='name,number,email\n';for(let i=0;i<n;i++){const name=names[i%names.length]+(i+1);s+=`${name},${Math.floor(Math.random()*10000)},${name.toLowerCase()}@example.com\n`}d.querySelector('#o').value=s};return d});
add('Data','csvclean','🧹','CSV Duplicate Cleaner','Remove duplicate rows from CSV text.',b=>{const d=fields(`<textarea id="i" rows="12"></textarea><button class="btn" id="go">Clean</button><textarea id="o" rows="12"></textarea>`);d.querySelector('#go').onclick=()=>d.querySelector('#o').value=[...new Set(d.querySelector('#i').value.split(/\r?\n/).filter(Boolean))].join('\n');return d});

// More Design
add('Design','contrast','◐','Color Contrast Checker','Check approximate WCAG contrast ratio for two colors.',b=>{const d=fields(`<div class="grid2"><input id="a" type="color" value="#000000"><input id="b" type="color" value="#ffffff"></div><button class="btn" id="go">Check</button><div id="o" class="out"></div>`);d.querySelector('#go').onclick=()=>{const lum=h=>{const x=[1,3,5].map(i=>parseInt(h.slice(i,i+2),16)/255).map(x=>x<=.03928?x/12.92:((x+.055)/1.055)**2.4);return .2126*x[0]+.7152*x[1]+.0722*x[2]};const a=lum(d.querySelector('#a').value),bb=lum(d.querySelector('#b').value),r=(Math.max(a,bb)+.05)/(Math.min(a,bb)+.05);d.querySelector('#o').textContent=`Contrast ratio: ${r.toFixed(2)}:1`};return d});
add('Design','svgpng','🖼️','SVG to PNG','Convert SVG markup to a PNG image.',b=>{const d=fields(`<textarea id="i" rows="12" placeholder="<svg ...></svg>"></textarea><button class="btn" id="go">Convert</button>`);d.querySelector('#go').onclick=async()=>{const blob=new Blob([d.querySelector('#i').value],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),im=await imageLoad(new File([blob],'x.svg',{type:'image/svg+xml'})),c=document.createElement('canvas');c.width=im.naturalWidth||800;c.height=im.naturalHeight||600;c.getContext('2d').drawImage(im,0,0);dl(await canvasBlob(c,'image/png'),'converted.png');URL.revokeObjectURL(url)};return d});

// More Study
add('Study','pomodoro','🍅','Pomodoro Timer','25/5 focus timer with short breaks.',b=>{const d=fields(`<div id="o" class="big">25:00</div><div class="actions"><button class="btn" id="s">Start</button><button class="btn secondary" id="r">Reset</button></div>`);let t,n=25*60,focus=true;const draw=()=>d.querySelector('#o').textContent=`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;d.querySelector('#s').onclick=()=>{clearInterval(t);t=setInterval(()=>{n--;draw();if(n<=0){clearInterval(t);focus=!focus;n=(focus?25:5)*60;alert(focus?'Focus time!':'Break time!')}},1000)};d.querySelector('#r').onclick=()=>{clearInterval(t);focus=true;n=1500;draw()};return d});
add('Study','randompicker','🎯','Random Picker','Pick one item from a list at random.',b=>{const d=fields(`<textarea id="i" rows="10" placeholder="One option per line"></textarea><button class="btn" id="go">Pick</button><div id="o" class="big"></div>`);d.querySelector('#go').onclick=()=>{const a=d.querySelector('#i').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);d.querySelector('#o').textContent=a.length?a[Math.floor(Math.random()*a.length)]:'Add options first'};return d});

// More Games
add('Games','snake','🐍','Snake','Classic snake game running entirely in the browser.',b=>{const d=fields(`<canvas id="c" width="320" height="320" style="max-width:100%;border:1px solid #ccc"></canvas><div class="out" id="o">Use arrow keys. Press Start.</div><button class="btn" id="s">Start</button>`);const c=d.querySelector('#c'),x=c.getContext('2d');let snake,food,dir,run,score;const place=()=>food={x:Math.floor(Math.random()*20),y:Math.floor(Math.random()*20)};const draw=()=>{x.clearRect(0,0,320,320);x.fillText('🍎',food.x*16+2,food.y*16+14);snake.forEach(p=>{x.fillRect(p.x*16,p.y*16,15,15)})};d.querySelector('#s').onclick=()=>{snake=[{x:10,y:10}];dir={x:1,y:0};score=0;place();clearInterval(run);run=setInterval(()=>{const h={x:snake[0].x+dir.x,y:snake[0].y+dir.y};if(h.x<0||h.y<0||h.x>=20||h.y>=20||snake.some(p=>p.x===h.x&&p.y===h.y)){clearInterval(run);return}snake.unshift(h);if(h.x===food.x&&h.y===food.y){score++;place()}else snake.pop();draw();d.querySelector('#o').textContent='Score: '+score},120);draw()};window.addEventListener('keydown',e=>{if(!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))return;const m={ArrowUp:{x:0,y:-1},ArrowDown:{x:0,y:1},ArrowLeft:{x:-1,y:0},ArrowRight:{x:1,y:0}}[e.key];if(dir&&m.x!==-dir.x&&m.y!==-dir.y)dir=m});return d});
add('Games','2048','🔢','2048 Mini','A compact 2048-style number game.',b=>{const d=fields(`<div id="g" style="display:grid;grid-template-columns:repeat(4,1fr);gap:5px"></div><div id="o" class="out">Use arrow keys.</div>`);let a=Array(16).fill(0);const spawn=()=>{const z=a.map((v,i)=>v?null:i).filter(v=>v!==null);if(z.length)a[z[Math.floor(Math.random()*z.length)]]=2};const draw=()=>d.querySelector('#g').innerHTML=a.map(v=>`<div style="padding:20px;text-align:center;border:1px solid #ccc">${v||''}</div>`).join('');const move=()=>{for(let r=0;r<4;r++){let row=a.slice(r*4,r*4+4).filter(Boolean);for(let i=0;i<row.length-1;i++)if(row[i]===row[i+1]){row[i]*=2;row.splice(i+1,1)};row=[...row,...Array(4-row.length).fill(0)];a.splice(r*4,4,...row)}spawn();draw()};spawn();spawn();draw();window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){for(let r=0;r<4;r++){let row=a.slice(r*4,r*4+4);if(e.key==='ArrowRight')row.reverse();let old=row.join(),tmp=row.filter(Boolean);for(let i=0;i<tmp.length-1;i++)if(tmp[i]===tmp[i+1]){tmp[i]*=2;tmp.splice(i+1,1)};row=[...tmp,...Array(4-tmp.length).fill(0)];if(e.key==='ArrowRight')row.reverse();a.splice(r*4,4,...row)}spawn();draw()}else if(['ArrowUp','ArrowDown'].includes(e.key)){const cols=[];for(let c=0;c<4;c++)cols.push([0,1,2,3].map(r=>a[r*4+c]));cols.forEach((col,c)=>{if(e.key==='ArrowDown')col.reverse();let tmp=col.filter(Boolean);for(let i=0;i<tmp.length-1;i++)if(tmp[i]===tmp[i+1]){tmp[i]*=2;tmp.splice(i+1,1)};col=[...tmp,...Array(4-tmp.length).fill(0)];if(e.key==='ArrowDown')col.reverse();col.forEach((v,r)=>a[r*4+c]=v)});spawn();draw()}});return d});

// Device utilities
add('Games','typing','⌨️','Typing Speed Test','Measure typing speed on a sample sentence.',b=>{const d=fields(`<p id="q">The quick brown fox jumps over the lazy dog.</p><textarea id="i" rows="4"></textarea><button class="btn" id="go">Check</button><div id="o" class="out"></div>`);const start=performance.now();d.querySelector('#go').onclick=()=>{const sec=(performance.now()-start)/60000,txt=d.querySelector('#i').value,wpm=Math.round((txt.trim().split(/\s+/).filter(Boolean).length)/sec);d.querySelector('#o').textContent=`Approx. ${wpm} WPM`};return d});
add('Developer','screen','🖥️','Screen Recorder','Record your screen using browser permission.',b=>{const d=fields(`<button class="btn" id="s">Start</button><button class="btn secondary" id="x">Stop</button><div id="o" class="out"></div>`);let r,ch=[];d.querySelector('#s').onclick=async()=>{const st=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});r=new MediaRecorder(st);ch=[];r.ondataavailable=e=>ch.push(e.data);r.onstop=()=>{st.getTracks().forEach(t=>t.stop());const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(ch,{type:'video/webm'}));a.download='screen-recording.webm';a.textContent='Download recording';d.querySelector('#o').replaceChildren(a)};r.start()};d.querySelector('#x').onclick=()=>r?.stop();return d});
add('Developer','webcam','📷','Webcam Recorder','Preview and record webcam video locally.',b=>{const d=fields(`<video id="v" autoplay muted playsinline style="max-width:100%"></video><div class="actions"><button class="btn" id="s">Start</button><button class="btn secondary" id="x">Stop</button></div><div id="o" class="out"></div>`);let st,r,ch=[];d.querySelector('#s').onclick=async()=>{st=await navigator.mediaDevices.getUserMedia({video:true,audio:true});d.querySelector('#v').srcObject=st;r=new MediaRecorder(st);ch=[];r.ondataavailable=e=>ch.push(e.data);r.onstop=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(ch,{type:'video/webm'}));a.download='webcam.webm';a.textContent='Download webcam video';d.querySelector('#o').replaceChildren(a)};r.start()};d.querySelector('#x').onclick=()=>{r?.stop();st?.getTracks().forEach(t=>t.stop())};return d});

function render(){const tb=document.createElement('table');tb.innerHTML=rows.map((r,i)=>'<tr>'+r.map((x,j)=>`<td contenteditable data-r=${i} data-c=${j}>${esc(x)}</td>`).join('')+'</tr>').join('');tb.querySelectorAll('td').forEach(c=>c.oninput=()=>rows[c.dataset.r][c.dataset.c]=c.textContent);d.querySelector('#o').replaceChildren(tb)}d.querySelector('#save').onclick=()=>dl(new Blob([csvString(rows)],{type:'text/csv'}),'data.csv');return d});
add('Data','jsoncsv','↔️','JSON ↔ CSV','Convert arrays of JSON objects and CSV.',b=>{const d=fields(`<textarea id=t rows=12 placeholder='[{"name":"A","score":10}]'></textarea><div class=actions><button class=btn id=jc>JSON → CSV</button><button class="btn secondary" id=cj>CSV → JSON</button></div><textarea id=o rows=12></textarea>`);d.querySelector('#jc').onclick=()=>{try{const a=JSON.parse(d.querySelector('#t').value),h=[...new Set(a.flatMap(x=>Object.keys(x)))];d.querySelector('#o').value=csvString([h,...a.map(x=>h.map(k=>x[k]??''))])}catch(e){d.querySelector('#o').value=e.message}};d.querySelector('#cj').onclick=()=>{try{const r=csvParse(d.querySelector('#t').value),h=r.shift();d.querySelector('#o').value=JSON.stringify(r.map(x=>Object.fromEntries(h.map((k,i)=>[k,x[i]??'']))),null,2)}catch(e){d.querySelector('#o').value=e.message}};return d});
// DESIGN
add('Design','editor','🎨','Simple Image Editor','Brightness, contrast, grayscale and text overlay.',b=>basicFileUI('image/*',async f=>{const im=await imageLoad(f),d=fields(`<div class=grid2><label>Brightness<input id=b type=range min=-1 max=1 step=.05 value=0></label><label>Contrast<input id=c type=range min=-1 max=1 step=.05 value=0></label><label>Text<input id=t placeholder="Optional text"></label><label>Text size<input id=s type=number value=32></label></div><div class=actions><button class=btn id=go>Apply & Download</button></div>`);document.querySelector('.drop')?.after(d);d.querySelector('#go').onclick=async()=>{const c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;const x=c.getContext('2d'),b=+d.querySelector('#b').value,co=+d.querySelector('#c').value;x.filter=`brightness(${1+b}) contrast(${1+co})`;x.drawImage(im,0,0);x.filter='none';x.fillStyle='white';x.strokeStyle='black';x.lineWidth=5;x.font=`bold ${+d.querySelector('#s').value}px Arial`;const t=d.querySelector('#t').value;if(t){x.strokeText(t,20,c.height-30);x.fillText(t,20,c.height-30)}dl(await canvasBlob(c,'image/png'),'edited.png')}}));
add('Design','meme','😂','Meme Maker','Put top and bottom text on an image.',b=>basicFileUI('image/*',async f=>{const im=await imageLoad(f),d=fields(`<div class=grid2><input id=t placeholder="Top text"><input id=b placeholder="Bottom text"></div><button class=btn id=go>Create Meme</button>`);document.querySelector('.drop')?.after(d);d.querySelector('#go').onclick=async()=>{const c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;x=c.getContext('2d');x.drawImage(im,0,0);x.textAlign='center';x.font=`bold ${Math.max(28,c.width/12)}px Impact,Arial`;x.lineWidth=8;x.fillStyle='white';x.strokeStyle='black';[['t',50],['b',c.height-30]].forEach(([id,y])=>{const t=d.querySelector('#'+id).value.toUpperCase();x.strokeText(t,c.width/2,y);x.fillText(t,c.width/2,y)});dl(await canvasBlob(c,'image/jpeg',.92),'meme.jpg')}}));
add('Design','qr','▦','QR Code Generator','Generate QR codes locally.',b=>{const d=fields(`<input id=t placeholder="Text or URL"><select id=s><option>4</option><option>6</option><option>8</option></select><button class=btn id=go>Generate QR</button><div id=o></div>`);d.querySelector('#go').onclick=()=>{if(!window.qrcode)return alert('QR library not loaded.');const q=qrcode(0,'M');q.addData(d.querySelector('#t').value);q.make();d.querySelector('#o').innerHTML=q.createImgTag(+d.querySelector('#s').value,4)};return d});
// DEVELOPER
add('Developer','format','🧰','Code Formatter','Basic formatter for HTML, CSS and JS.',b=>{const d=fields(`<select id=k><option>HTML</option><option>CSS</option><option>JS</option></select><textarea id=t rows=15></textarea><button class=btn id=go>Format</button><textarea id=o rows=15 readonly></textarea>`);d.querySelector('#go').onclick=()=>{let s=d.querySelector('#t').value.trim(),k=d.querySelector('#k').value;if(k==='HTML')s=s.replace(/></g,'>\n<').split('\n').map((l,i)=>'  '.repeat(Math.min(6,(l.match(/^<\/?/)?(l.startsWith('</')?-1:1):0)+i%2))+l).join('\n');else s=s.replace(/\s*([{};])\s*/g,'$1\n').replace(/\n+/g,'\n').split('\n').map(x=>x.trim()).join('\n');d.querySelector('#o').value=s};return d});
add('Developer','base64','🔤','Base64 Encoder / Decoder','Encode or decode UTF-8 text.',b=>{const d=fields(`<textarea id=t rows=8></textarea><div class=actions><button class=btn id=e>Encode</button><button class="btn secondary" id=x>Decode</button></div><textarea id=o rows=8></textarea>`);d.querySelector('#e').onclick=()=>d.querySelector('#o').value=btoa(unescape(encodeURIComponent(d.querySelector('#t').value)));d.querySelector('#x').onclick=()=>{try{d.querySelector('#o').value=decodeURIComponent(escape(atob(d.querySelector('#t').value)))}catch(e){d.querySelector('#o').value='Invalid Base64'}};return d});
add('Developer','regex','🔎','Regex Tester','Test a regular expression against text.',b=>{const d=fields(`<div class=grid2><input id=r placeholder="\\d+"><input id=f placeholder="g"></div><textarea id=t rows=10></textarea><button class=btn id=go>Test</button><div id=o class=out></div>`);d.querySelector('#go').onclick=()=>{try{const re=new RegExp(d.querySelector('#r').value,d.querySelector('#f').value),s=d.querySelector('#t').value,m=[...s.matchAll(re)];d.querySelector('#o').textContent=`Matches: ${m.length}\n`+m.map(x=>x[0]).join('\n')}catch(e){d.querySelector('#o').textContent=e.message}};return d});
// STUDY
add('Study','quiz','❓','Quiz Maker','Create a quick local multiple-choice quiz.',b=>{const d=fields(`<textarea id=q rows=12 placeholder="Question | Answer | Wrong1 | Wrong2"></textarea><button class=btn id=go>Start Quiz</button><div id=o class=out></div>`);d.querySelector('#go').onclick=()=>{const qs=d.querySelector('#q').value.trim().split(/\n/).map(x=>x.split('|'));let i=0,score=0;const next=()=>{if(i>=qs.length){d.querySelector('#o').innerHTML=`<div class=big>Score ${score}/${qs.length}</div>`;return}const q=qs[i],opts=[q[1],q[2],q[3]].filter(Boolean).sort(()=>Math.random()-.5);d.querySelector('#o').innerHTML=`<h3>${esc(q[0])}</h3>`+opts.map(x=>`<button class="btn opt" data-a="${esc(x)}">${esc(x)}</button> `);d.querySelectorAll('.opt').forEach(x=>x.onclick=()=>{if(x.dataset.a===q[1])score++;i++;next()})};next()};return d});
add('Study','flash','🗂️','Flashcards','Create simple front/back cards and study them.',b=>{const d=fields(`<textarea id=t rows=10 placeholder="Front | Back"></textarea><button class=btn id=go>Start</button><div id=o class=out></div>`);d.querySelector('#go').onclick=()=>{const a=d.querySelector('#t').value.trim().split(/\n/).map(x=>x.split('|'));let i=0,show=false;const draw=()=>{if(i>=a.length){d.querySelector('#o').textContent='Finished!';return}d.querySelector('#o').innerHTML=`<div class=big>${esc(show?a[i][1]:a[i][0])}</div><div class=actions><button class=btn id=f>${show?'Next':'Reveal'}</button></div>`;d.querySelector('#f').onclick=()=>{if(show){i++;show=false}else show=true;draw()}};draw()};return d});
add('Study','timer','⏱️','Study Timer','Countdown timer for focused study.',b=>{const d=fields(`<div class=timer><div id=o class=big>25:00</div><input id=m type=number value=25 min=1><div class=actions><button class=btn id=s>Start</button><button class="btn secondary" id=r>Reset</button></div></div>`);let timer;d.querySelector('#s').onclick=()=>{clearInterval(timer);let n=+d.querySelector('#m').value*60;timer=setInterval(()=>{d.querySelector('#o').textContent=`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;if(n--<=0)clearInterval(timer)},1000)};d.querySelector('#r').onclick=()=>{clearInterval(timer);d.querySelector('#o').textContent=`${String(+d.querySelector('#m').value).padStart(2,'0')}:00`};return d});
// GAMES
add('Games','click','🎯','Click Speed Game','Click the target as many times as possible in 10 seconds.',b=>{const d=fields(`<div class=game id=g><button class=target id=t>🎯</button></div><div class=out id=o>Score: 0 • Time: 10</div><button class=btn id=s>Start</button>`);let score=0,n=10,timer;d.querySelector('#s').onclick=()=>{score=0;n=10;d.querySelector('#o').textContent='Score: 0 • Time: 10';clearInterval(timer);timer=setInterval(()=>{n--;d.querySelector('#o').textContent=`Score: ${score} • Time: ${n}`;if(n<=0)clearInterval(timer)},1000);move();};d.querySelector('#t').onclick=()=>{if(n>0){score++;move()}};function move(){const g=d.querySelector('#g'),t=d.querySelector('#t');t.style.left=Math.random()*(g.clientWidth-50)+'px';t.style.top=Math.random()*(g.clientHeight-50)+'px'}return d});
add('Games','reaction','⚡','Reaction Test','Wait for green, then click as fast as you can.',b=>{const d=fields(`<div id=g class=game></div><div id=o class=out>Press Start.</div><button class=btn id=s>Start</button>`);let go=0,start=0;d.querySelector('#s').onclick=()=>{const g=d.querySelector('#g');g.textContent='Wait…';g.style.background='#f7f7fa';setTimeout(()=>{g.textContent='CLICK!';g.style.background='#dff7df';go=1;start=performance.now()},700+Math.random()*1800)};d.querySelector('#g').onclick=()=>{if(go){d.querySelector('#o').textContent=`Reaction: ${Math.round(performance.now()-start)} ms`;go=0}};return d});
add('Games','memory','🧠','Memory Match','Match pairs of symbols.',b=>{const d=fields(`<div id=g class=cards></div><div id=o class=out>Find all pairs.</div>`);const a=['🍎','🍌','🍇','🍒','🥝','🍉','🍎','🍌','🍇','🍒','🥝','🍉'].sort(()=>Math.random()-.5);let open=[],matched=0;a.forEach((x,i)=>{const c=document.createElement('button');c.className='card';c.textContent='❔';c.onclick=()=>{if(open.length>=2||c.dataset.done)return;c.textContent=x;open.push({c,x});if(open.length===2){if(open[0].x===open[1].x){open.forEach(z=>z.c.dataset.done=1);matched+=2;open=[]}else setTimeout(()=>{open.forEach(z=>z.c.textContent='❔');open=[]},500)}if(matched===a.length)d.querySelector('#o').textContent='You matched them all!'};d.querySelector('#g').append(c)});return d});

// ================= EXTRA BROWSER-ONLY TOOLS =================
const blobFromText=(text,type='text/plain')=>new Blob([text],{type});
const downloadText=(text,name,type='text/plain')=>dl(blobFromText(text,type),name);
const wrapTool=(html,fn)=>{const d=fields(html);fn(d);return d};
const readText=f=>f.text();
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));

// More Image tools
add('Image','filters','🎛️','Image Filters','Brightness, contrast, saturation, grayscale and blur.',b=>basicFileUI('image/*',async f=>{const im=await imageLoad(f),d=fields(`<div class="grid2"><label>Brightness<input id="br" type="range" min="0" max="2" step=".05" value="1"></label><label>Contrast<input id="co" type="range" min="0" max="2" step=".05" value="1"></label><label>Saturation<input id="sa" type="range" min="0" max="2" step=".05" value="1"></label><label>Blur<input id="bl" type="range" min="0" max="12" step="1" value="0"></label></div><div class="actions"><button class="btn" id="go">Apply & Download</button></div>`);document.querySelector('.drop')?.after(d);d.querySelector('#go').onclick=async()=>{const c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;const x=c.getContext('2d');x.filter=`brightness(${d.querySelector('#br').value}) contrast(${d.querySelector('#co').value}) saturate(${d.querySelector('#sa').value}) blur(${d.querySelector('#bl').value}px)`;x.drawImage(im,0,0);dl(await canvasBlob(c,'image/png'),'filtered.png')}}));
add('Image','pixelate','🔲','Pixelate Image','Create a pixelated privacy effect.',b=>basicFileUI('image/*',async f=>{const im=await imageLoad(f),d=fields(`<label>Pixel size<input id="n" type="number" min="2" max="100" value="12"></label><button class="btn" id="go">Pixelate</button>`);document.querySelector('.drop')?.after(d);d.querySelector('#go').onclick=async()=>{const n=+d.querySelector('#n').value,c=document.createElement('canvas'),x=c.getContext('2d');c.width=im.naturalWidth;c.height=im.naturalHeight;const sw=Math.max(1,Math.floor(c.width/n)),sh=Math.max(1,Math.floor(c.height/n));const s=document.createElement('canvas');s.width=sw;s.height=sh;s.getContext('2d').drawImage(im,0,0,sw,sh);x.imageSmoothingEnabled=false;x.drawImage(s,0,0,c.width,c.height);dl(await canvasBlob(c,'image/png'),'pixelated.png')}}));
add('Image','contact','🧩','Contact Sheet','Combine multiple images into one contact sheet.',b=>basicFileUI('image/*',async fs=>{if(!fs?.length)return;const ims=await Promise.all(fs.map(imageLoad)),cols=3,cell=220,rows=Math.ceil(ims.length/cols),c=document.createElement('canvas');c.width=cols*cell;c.height=rows*cell;const x=c.getContext('2d');ims.forEach((im,i)=>{const cx=(i%cols)*cell,cy=Math.floor(i/cols)*cell,sc=Math.min(cell/im.naturalWidth,cell/im.naturalHeight);x.drawImage(im,cx+(cell-im.naturalWidth*sc)/2,cy+(cell-im.naturalHeight*sc)/2,im.naturalWidth*sc,im.naturalHeight*sc)});dl(await canvasBlob(c,'image/png'),'contact-sheet.png')},true));
add('Image','favicon','🌐','Favicon Generator','Create a 64×64 PNG favicon from an image.',b=>basicFileUI('image/*',async f=>{const im=await imageLoad(f),c=document.createElement('canvas');c.width=c.height=64;c.getContext('2d').drawImage(im,0,0,64,64);dl(await canvasBlob(c,'image/png'),'favicon.png')}));
add('Image','social','📐','Social Image Resizer','Resize an image to common social-media canvas sizes.',b=>basicFileUI('image/*',async f=>{const im=await imageLoad(f),d=fields(`<select id="p"><option value="1080x1080">Square 1080×1080</option><option value="1080x1920">Story/Short 1080×1920</option><option value="1280x720">Video 1280×720</option><option value="1200x630">Link/OG 1200×630</option></select><button class="btn" id="go">Resize</button>`);document.querySelector('.drop')?.after(d);d.querySelector('#go').onclick=async()=>{const [w,h]=d.querySelector('#p').value.split('x').map(Number),c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,w,h);const sc=Math.min(w/im.naturalWidth,h/im.naturalHeight);x.drawImage(im,(w-im.naturalWidth*sc)/2,(h-im.naturalHeight*sc)/2,im.naturalWidth*sc,im.naturalHeight*sc);dl(await canvasBlob(c,'image/png'),'social-'+w+'x'+h+'.png')}}));
add('Image','palette','🎨','Color Palette Extractor','Extract a simple dominant color palette from an image.',b=>basicFileUI('image/*',async f=>{const im=await imageLoad(f),c=document.createElement('canvas');c.width=50;c.height=50;c.getContext('2d').drawImage(im,0,0,50,50);const data=c.getContext('2d').getImageData(0,0,50,50).data, buckets={};for(let i=0;i<data.length;i+=16){const r=Math.round(data[i]/32)*32,g=Math.round(data[i+1]/32)*32,bl=Math.round(data[i+2]/32)*32,k=`${clamp(r,0,255)},${clamp(g,0,255)},${clamp(bl,0,255)}`;buckets[k]=(buckets[k]||0)+1}const top=Object.entries(buckets).sort((a,b)=>b[1]-a[1]).slice(0,8).map(x=>'#'+x[0].split(',').map(v=>Number(v).toString(16).padStart(2,'0')).join(''));b.innerHTML=`<div class="out">${top.map(x=>`<div style="display:inline-block;margin:5px;padding:12px;border-radius:8px;background:${x};color:${parseInt(x.slice(1),16)>0xffffff/2?'#000':'#fff'}">${x}</div>`).join('')}</div>`}));
add('Image','ascii','🔤','Image to ASCII','Convert an image into text art.',b=>basicFileUI('image/*',async f=>{const im=await imageLoad(f),c=document.createElement('canvas'),w=80,h=Math.max(1,Math.round(80*im.naturalHeight/im.naturalWidth*.5));c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);const d=c.getContext('2d').getImageData(0,0,w,h).data,ch='@%#*+=-:. ';let out='';for(let y=0;y<h;y++){for(let x=0;x<w;x++){const i=(y*w+x)*4,g=.299*d[i]+.587*d[i+1]+.114*d[i+2];out+=ch[Math.floor(g/256*ch.length)]}out+='\n'}const o=fields(`<pre class="out"></pre><button class="btn" id="dl">Download TXT</button>`);o.querySelector('pre').textContent=out;o.querySelector('#dl').onclick=()=>downloadText(out,'ascii.txt');document.querySelector('.drop')?.after(o)}));

// More Audio tools
function audioDecode(f){return f.arrayBuffer().then(buf=>new AudioContext().decodeAudioData(buf));}
add('Audio','speed','🐇','Audio Speed Changer','Change playback speed and export WAV.',b=>basicFileUI('audio/*',async f=>{const d=fields(`<label>Speed<input id="s" type="range" min=".5" max="2" step=".05" value="1"></label><button class="btn" id="go">Export WAV</button>`);document.querySelector('.drop')?.after(d);d.querySelector('#go').onclick=async()=>{const src=await audioDecode(f),rate=src.sampleRate,dur=src.duration/+d.querySelector('#s').value,off=new OfflineAudioContext(src.numberOfChannels,Math.ceil(dur*rate),rate),node=off.createBufferSource();node.buffer=src;node.playbackRate.value=+d.querySelector('#s').value;node.connect(off.destination);node.start();const out=await off.startRendering();dl(wavBlob(out),'audio-speed.wav')}}));
function wavBlob(buf){const ch=buf.numberOfChannels,rate=buf.sampleRate,len=buf.length*ch,ab=new ArrayBuffer(44+len*2),v=new DataView(ab),w=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))};w(0,'RIFF');v.setUint32(4,36+len*2,true);w(8,'WAVE');w(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,ch,true);v.setUint32(24,rate,true);v.setUint32(28,rate*ch*2,true);v.setUint16(32,ch*2,true);v.setUint16(34,16,true);w(36,'data');v.setUint32(40,len*2,true);let o=44;for(let i=0;i<buf.length;i++)for(let c=0;c<ch;c++){const s=clamp(buf.getChannelData(c)[i],-1,1);v.setInt16(o,s<0?s*0x8000:s*0x7fff,true);o+=2}return new Blob([v],{type:'audio/wav'})}
add('Audio','fade','🌅','Audio Fade In / Out','Apply fade-in and fade-out and export WAV.',b=>basicFileUI('audio/*',async f=>{const d=fields(`<div class="grid2"><label>Fade in sec<input id="i" type="number" min="0" value="1"></label><label>Fade out sec<input id="o" type="number" min="0" value="1"></label></div><button class="btn" id="go">Export WAV</button>`);document.querySelector('.drop')?.after(d);d.querySelector('#go').onclick=async()=>{const src=await audioDecode(f),off=new OfflineAudioContext(src.numberOfChannels,src.length,src.sampleRate),n=off.createBufferSource(),g=off.createGain();n.buffer=src;g.gain.setValueAtTime(0,0);g.gain.linearRampToValueAtTime(1,Math.min(+d.querySelector('#i').value,src.duration));const fo=Math.max(0,src.duration-+d.querySelector('#o').value);g.gain.setValueAtTime(1,fo);g.gain.linearRampToValueAtTime(0,src.duration);n.connect(g).connect(off.destination);n.start();dl(wavBlob(await off.startRendering()),'faded.wav')}}));
add('Audio','merge','🔗','Merge Audio Files','Join audio files sequentially and export WAV.',b=>basicFileUI('audio/*',async fs=>{const arr=await Promise.all(fs.map(audioDecode));const rate=arr[0].sampleRate,ch=Math.max(...arr.map(x=>x.numberOfChannels)),len=arr.reduce((n,x)=>n+x.length,0),off=new OfflineAudioContext(ch,len,rate);let t=0;arr.forEach(a=>{const n=off.createBufferSource();n.buffer=a;n.connect(off.destination);n.start(t/rate);t+=a.length});dl(wavBlob(await off.startRendering()),'merged.wav')},true));
add('Audio','recorder','🎙️','Audio Recorder','Record microphone audio locally as WebM/Opus.',b=>{const d=fields(`<button class="btn" id="s">Start</button><button class="btn secondary" id="x">Stop</button><div id="o" class="out"></div>`);let rec,ch=[];d.querySelector('#s').onclick=async()=>{const st=await navigator.mediaDevices.getUserMedia({audio:true});rec=new MediaRecorder(st);ch=[];rec.ondataavailable=e=>ch.push(e.data);rec.onstop=()=>{st.getTracks().forEach(t=>t.stop());const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(ch,{type:'audio/webm'}));a.download='recording.webm';a.textContent='Download recording';d.querySelector('#o').replaceChildren(a)};rec.start()};d.querySelector('#x').onclick=()=>rec?.stop();return d});

// More Text / Data / Developer
add('Text','duplicates','🧹','Remove Duplicate Lines','Remove repeated lines from text.',b=>{const d=fields(`<textarea id="i" rows="14"></textarea><button class="btn" id="go">Remove Duplicates</button><textarea id="o" rows="14"></textarea>`);d.querySelector('#go').onclick=()=>d.querySelector('#o').value=[...new Set(d.querySelector('#i').value.split(/\r?\n/))].join('\n');return d});
add('Text','sortlines','↕️','Sort Lines','Sort text lines alphabetically.',b=>{const d=fields(`<textarea id="i" rows="12"></textarea><button class="btn" id="go">Sort</button><textarea id="o" rows="12"></textarea>`);d.querySelector('#go').onclick=()=>d.querySelector('#o').value=d.querySelector('#i').value.split(/\r?\n/).sort((a,b)=>a.localeCompare(b)).join('\n');return d});
add('Text','slug','🔗','Slug Generator','Turn a title into a clean URL slug.',b=>{const d=fields(`<input id="i" placeholder="My Great Article"><button class="btn" id="go">Generate</button><input id="o" readonly>`);d.querySelector('#go').onclick=()=>d.querySelector('#o').value=d.querySelector('#i').value.toLowerCase().trim().replace(/[^\w\s-]/g,'').replace(/[\s_-]+/g,'-').replace(/^-+|-+$/g,'');return d});
add('Text','diff','🌓','Text Diff','Compare two text blocks and show changed lines.',b=>{const d=fields(`<textarea id="a" rows="10" placeholder="Original"></textarea><textarea id="b" rows="10" placeholder="New"></textarea><button class="btn" id="go">Compare</button><pre id="o" class="out"></pre>`);d.querySelector('#go').onclick=()=>{const a=d.querySelector('#a').value.split(/\r?\n/),bb=d.querySelector('#b').value.split(/\r?\n/),setA=new Set(a),setB=new Set(bb);d.querySelector('#o').textContent='Removed:\n'+a.filter(x=>!setB.has(x)).map(x=>'- '+x).join('\n')+'\n\nAdded:\n'+bb.filter(x=>!setA.has(x)).map(x=>'+ '+x).join('\n')};return d});
add('Text','url','🔗','URL Encoder / Decoder','Encode or decode URL text.',b=>{const d=fields(`<textarea id="i" rows="8"></textarea><button class="btn" id="e">Encode</button><button class="btn secondary" id="x">Decode</button><textarea id="o" rows="8"></textarea>`);d.querySelector('#e').onclick=()=>d.querySelector('#o').value=encodeURIComponent(d.querySelector('#i').value);d.querySelector('#x').onclick=()=>{try{d.querySelector('#o').value=decodeURIComponent(d.querySelector('#i').value)}catch(e){d.querySelector('#o').value='Invalid encoded URL'}};return d});
add('Text','entities','&lt;&gt;','HTML Entity Encoder','Encode or decode HTML entities.',b=>{const d=fields(`<textarea id="i" rows="8"></textarea><button class="btn" id="e">Encode</button><button class="btn secondary" id="x">Decode</button><textarea id="o" rows="8"></textarea>`);d.querySelector('#e').onclick=()=>d.querySelector('#o').value=d.querySelector('#i').value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');d.querySelector('#x').onclick=()=>{const t=document.createElement('textarea');t.innerHTML=d.querySelector('#i').value;d.querySelector('#o').value=t.value};return d});
add('Developer','jsonvalidate','✅','JSON Validator','Validate JSON and inspect its formatted structure.',b=>{const d=fields(`<textarea id="i" rows="14"></textarea><button class="btn" id="go">Validate</button><div id="o" class="out"></div>`);d.querySelector('#go').onclick=()=>{try{const x=JSON.parse(d.querySelector('#i').value);d.querySelector('#o').textContent='Valid JSON\n'+JSON.stringify(x,null,2)}catch(e){d.querySelector('#o').textContent='Invalid JSON: '+e.message}};return d});
add('Developer','jsonmin','🗜️','JSON Minifier','Minify JSON for compact output.',b=>{const d=fields(`<textarea id="i" rows="12"></textarea><button class="btn" id="go">Minify</button><textarea id="o" rows="12"></textarea>`);d.querySelector('#go').onclick=()=>{try{d.querySelector('#o').value=JSON.stringify(JSON.parse(d.querySelector('#i').value))}catch(e){d.querySelector('#o').value='Invalid JSON'}};return d});
add('Developer','jwt','🪪','JWT Decoder','Decode JWT header and payload locally; no verification.',b=>{const d=fields(`<textarea id="i" rows="5" placeholder="eyJ..."></textarea><button class="btn" id="go">Decode</button><pre id="o" class="out"></pre>`);d.querySelector('#go').onclick=()=>{try{const p=d.querySelector('#i').value.split('.');const dec=x=>JSON.parse(decodeURIComponent(escape(atob(x.replace(/-/g,'+').replace(/_/g,'/')))));d.querySelector('#o').textContent='Header:\n'+JSON.stringify(dec(p[0]),null,2)+'\n\nPayload:\n'+JSON.stringify(dec(p[1]),null,2)}catch(e){d.querySelector('#o').textContent='Invalid JWT format'}};return d});
add('Developer','timestamp','🕒','Unix Timestamp Converter','Convert Unix timestamps and dates.',b=>{const d=fields(`<input id="i" placeholder="e.g. 1791050000"><div class="actions"><button class="btn" id="a">Timestamp → Date</button><button class="btn secondary" id="b">Date → Timestamp</button></div><div id="o" class="out"></div>`);d.querySelector('#a').onclick=()=>{const n=Number(d.querySelector('#i').value);d.querySelector('#o').textContent=Number.isFinite(n)?new Date(n*1000).toISOString():'Invalid timestamp'};d.querySelector('#b').onclick=()=>{const x=new Date(d.querySelector('#i').value);d.querySelector('#o').textContent=isNaN(x)?'Invalid date':Math.floor(x.getTime()/1000)};return d});
add('Developer','sql','🗃️','SQL Formatter','Basic SQL readability formatter.',b=>{const d=fields(`<textarea id="i" rows="12"></textarea><button class="btn" id="go">Format SQL</button><textarea id="o" rows="12"></textarea>`);d.querySelector('#go').onclick=()=>{let s=d.querySelector('#i').value.replace(/\s+/g,' ').trim();['SELECT','FROM','WHERE','GROUP BY','ORDER BY','HAVING','LIMIT','VALUES','SET','JOIN','LEFT JOIN','RIGHT JOIN','INNER JOIN','UNION'].forEach(k=>s=s.replace(new RegExp('\\s+'+k+'\\s+','ig'),'\n'+k+' '));d.querySelector('#o').value=s};return d});
add('Developer','cssgradient','🌈','CSS Gradient Generator','Generate a CSS linear gradient.',b=>{const d=fields(`<div class="grid2"><input id="a" type="color" value="#6d5dfc"><input id="b" type="color" value="#00c2ff"></div><input id="d" type="number" value="90"><button class="btn" id="go">Generate</button><pre id="o" class="out"></pre>`);d.querySelector('#go').onclick=()=>d.querySelector('#o').textContent=`background: linear-gradient(${+d.querySelector('#d').value}deg, ${d.querySelector('#a').value}, ${d.querySelector('#b').value});`;return d});
add('Developer','shadow','◼️','CSS Box Shadow Generator','Generate a ready-to-copy box-shadow rule.',b=>{const d=fields(`<div class="grid2"><input id="x" type="number" value="4"><input id="y" type="number" value="8"><input id="b" type="number" value="20"><input id="s" type="number" value="0"></div><input id="c" type="color" value="#000000"><button class="btn" id="go">Generate</button><pre id="o" class="out"></pre>`);d.querySelector('#go').onclick=()=>d.querySelector('#o').textContent=`box-shadow: ${d.querySelector('#x').value}px ${d.querySelector('#y').value}px ${d.querySelector('#b').value}px ${d.querySelector('#s').value}px ${d.querySelector('#c').value};`;return d});
add('Developer','mime','📦','MIME Type Lookup','Look up common file MIME types.',b=>{const d=fields(`<input id="i" placeholder=".pdf or pdf"><button class="btn" id="go">Lookup</button><div id="o" class="out"></div>`);const m={pdf:'application/pdf',jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',gif:'image/gif',svg:'image/svg+xml',txt:'text/plain',html:'text/html',css:'text/css',js:'text/javascript',json:'application/json',csv:'text/csv',mp3:'audio/mpeg',wav:'audio/wav',mp4:'video/mp4',webm:'video/webm',zip:'application/zip'};d.querySelector('#go').onclick=()=>{let k=d.querySelector('#i').value.toLowerCase().replace(/^\./,'');d.querySelector('#o').textContent=m[k]||'MIME type not in local list'};return d});

// More Security
add('Security','uuid','🆔','UUID Generator','Generate random UUID v4 values locally.',b=>{const d=fields(`<input id="n" type="number" min="1" max="100" value="5"><button class="btn" id="go">Generate</button><textarea id="o" rows="10"></textarea>`);d.querySelector('#go').onclick=()=>{const n=clamp(+d.querySelector('#n').value,1,100);d.querySelector('#o').value=Array.from({length:n},()=>crypto.randomUUID()).join('\n')};return d});
add('Security','hashfile','#️⃣','File SHA-256 Hash','Calculate a file checksum locally.',b=>basicFileUI('*/*',async f=>{if(!f)return;const h=await crypto.subtle.digest('SHA-256',await f.arrayBuffer()),hex=[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('');const d=fields(`<div class="out">SHA-256<br><code>${hex}</code></div>`);document.querySelector('.drop')?.after(d)}));
add('Security','token','🎲','Random Token Generator','Generate cryptographically strong random tokens.',b=>{const d=fields(`<input id="n" type="number" min="8" max="256" value="32"><button class="btn" id="go">Generate</button><textarea id="o" rows="5"></textarea>`);d.querySelector('#go').onclick=()=>{const n=clamp(+d.querySelector('#n').value,8,256),a=new Uint8Array(n);crypto.getRandomValues(a);d.querySelector('#o').value=[...a].map(x=>x.toString(16).padStart(2,'0')).join('')};return d});
add('Security','totp','⏱️','TOTP Generator','Generate a one-time code from a Base32 secret locally.',b=>{const d=fields(`<input id="s" placeholder="BASE32 SECRET"><button class="btn" id="go">Generate</button><div id="o" class="big"></div><small>This is a local utility; check your account provider's setup rules.</small>`);d.querySelector('#go').onclick=async()=>{try{const sec=d.querySelector('#s').value.replace(/=+$/,'').toUpperCase();const alph='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits='';for(const ch of sec){const n=alph.indexOf(ch);if(n<0)throw Error('Invalid Base32');bits+=n.toString(2).padStart(5,'0')}const bytes=new Uint8Array(Math.floor(bits.length/8));for(let i=0;i<bytes.length;i++)bytes[i]=parseInt(bits.slice(i*8,i*8+8),2);const key=await crypto.subtle.importKey('raw',bytes,{name:'HMAC',hash:'SHA-1'},false,['sign']);const ctr=Math.floor(Date.now()/1000/30);const msg=new ArrayBuffer(8),v=new DataView(msg);v.setUint32(4,ctr);const sig=new Uint8Array(await crypto.subtle.sign('HMAC',key,msg));const off=sig[sig.length-1]&15;const code=((sig[off]&127)<<24|(sig[off+1]<<16)|(sig[off+2]<<8)|sig[off+3])%1000000;d.querySelector('#o').textContent=String(code).padStart(6,'0')}catch(e){d.querySelector('#o').textContent='Invalid secret'}};return d});

// More Calculators
const calc=(cat,id,icon,title,desc,html,fn)=>add(cat,id,icon,title,desc,b=>{const d=fields(html);d.querySelector('#go').onclick=()=>d.querySelector('#o').textContent=fn(d);return d});
calc('Calculator','discount','🏷️','Discount Calculator','Calculate sale price and savings.','<div class="grid2"><input id="p" type="number" placeholder="Price"><input id="r" type="number" placeholder="Discount %"></div><button class="btn" id="go">Calculate</button><div id="o" class="out"></div>',d=>{const p=+d.querySelector('#p').value,r=+d.querySelector('#r').value,s=p*r/100;return `Savings: ${s.toFixed(2)}\nFinal price: ${(p-s).toFixed(2)}`});
calc('Calculator','gst','🧾','GST Calculator','Calculate GST-inclusive or exclusive price.','<div class="grid2"><input id="p" type="number" placeholder="Amount"><input id="r" type="number" value="18" placeholder="GST %"></div><button class="btn" id="go">Calculate</button><div id="o" class="out"></div>',d=>{const p=+d.querySelector('#p').value,r=+d.querySelector('#r').value;return `GST: ${(p*r/100).toFixed(2)}\nTotal: ${(p*(1+r/100)).toFixed(2)}`});
calc('Calculator','profit','📈','Profit / Loss Calculator','Calculate profit, loss and percentage.','<div class="grid2"><input id="c" type="number" placeholder="Cost price"><input id="s" type="number" placeholder="Selling price"></div><button class="btn" id="go">Calculate</button><div id="o" class="out"></div>',d=>{const c=+d.querySelector('#c').value,s=+d.querySelector('#s').value,p=s-c;return `${p>=0?'Profit':'Loss'}: ${Math.abs(p).toFixed(2)}\nPercentage: ${(Math.abs(p)/c*100).toFixed(2)}%`});
calc('Calculator','age','🎂','Age Calculator','Calculate age from date of birth.','<input id="d" type="date"><button class="btn" id="go">Calculate</button><div id="o" class="out"></div>',d=>{const x=new Date(d.querySelector('#d').value),n=new Date();let y=n.getFullYear()-x.getFullYear();if(n<new Date(n.getFullYear(),x.getMonth(),x.getDate()))y--;return `${y} years old`});
calc('Calculator','datediff','📅','Date Difference','Calculate the number of days between two dates.','<div class="grid2"><input id="a" type="date"><input id="b" type="date"></div><button class="btn" id="go">Calculate</button><div id="o" class="out"></div>',d=>{const a=new Date(d.querySelector('#a').value),b=new Date(d.querySelector('#b').value);return `${Math.round(Math.abs(b-a)/86400000)} days`});
calc('Calculator','bmi','⚖️','BMI Calculator','Calculate BMI from height and weight.','<div class="grid2"><input id="w" type="number" placeholder="Weight kg"><input id="h" type="number" placeholder="Height cm"></div><button class="btn" id="go">Calculate</button><div id="o" class="out"></div>',d=>{const w=+d.querySelector('#w').value,h=+d.querySelector('#h').value/100;return `BMI: ${(w/(h*h)).toFixed(1)}`});
calc('Calculator','base','🔢','Number Base Converter','Convert decimal, binary and hexadecimal values.','<input id="i" placeholder="255"><select id="b"><option value="10">Decimal</option><option value="2">Binary</option><option value="16">Hexadecimal</option></select><button class="btn" id="go">Convert</button><div id="o" class="out"></div>',d=>{const n=parseInt(d.querySelector('#i').value,+d.querySelector('#b').value);return `Decimal: ${n}\nBinary: ${n.toString(2)}\nHex: ${n.toString(16).toUpperCase()}`});
calc('Calculator','ratio','➗','Ratio Calculator','Simplify a two-number ratio.','<div class="grid2"><input id="a" type="number"><input id="b" type="number"></div><button class="btn" id="go">Simplify</button><div id="o" class="out"></div>',d=>{let a=Math.abs(+d.querySelector('#a').value),b=Math.abs(+d.querySelector('#b').value);const g=(x,y)=>y?g(y,x%y):x;const z=g(a,b);return `${a/z}:${b/z}`});

// More Data
add('Data','csvjson','🔄','CSV ↔ JSON','Convert simple CSV data to JSON and back.',b=>{const d=fields(`<textarea id="i" rows="12" placeholder="name,age\nA,10"></textarea><div class="actions"><button class="btn" id="cj">CSV → JSON</button><button class="btn secondary" id="jc">JSON → CSV</button></div><textarea id="o" rows="12"></textarea>`);d.querySelector('#cj').onclick=()=>{const rows=d.querySelector('#i').value.trim().split(/\r?\n/).map(x=>x.split(',')),h=rows.shift();d.querySelector('#o').value=JSON.stringify(rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]??'']))),null,2)};d.querySelector('#jc').onclick=()=>{try{const a=JSON.parse(d.querySelector('#i').value),h=[...new Set(a.flatMap(x=>Object.keys(x)))];d.querySelector('#o').value=[h.join(','),...a.map(x=>h.map(k=>String(x[k]??'').replace(/,/g,' ')).join(','))].join('\n')}catch(e){d.querySelector('#o').value='Invalid JSON'}};return d});
add('Data','randomdata','🎲','Random Data Generator','Generate sample names, numbers and emails for testing.',b=>{const d=fields(`<input id="n" type="number" min="1" max="500" value="20"><button class="btn" id="go">Generate CSV</button><textarea id="o" rows="14"></textarea>`);d.querySelector('#go').onclick=()=>{const n=clamp(+d.querySelector('#n').value,1,500),names=['Aman','Riya','Kabir','Neha','Arjun','Sara'];let s='name,number,email\n';for(let i=0;i<n;i++){const name=names[i%names.length]+(i+1);s+=`${name},${Math.floor(Math.random()*10000)},${name.toLowerCase()}@example.com\n`}d.querySelector('#o').value=s};return d});
add('Data','csvclean','🧹','CSV Duplicate Cleaner','Remove duplicate rows from CSV text.',b=>{const d=fields(`<textarea id="i" rows="12"></textarea><button class="btn" id="go">Clean</button><textarea id="o" rows="12"></textarea>`);d.querySelector('#go').onclick=()=>d.querySelector('#o').value=[...new Set(d.querySelector('#i').value.split(/\r?\n/).filter(Boolean))].join('\n');return d});

// More Design
add('Design','contrast','◐','Color Contrast Checker','Check approximate WCAG contrast ratio for two colors.',b=>{const d=fields(`<div class="grid2"><input id="a" type="color" value="#000000"><input id="b" type="color" value="#ffffff"></div><button class="btn" id="go">Check</button><div id="o" class="out"></div>`);d.querySelector('#go').onclick=()=>{const lum=h=>{const x=[1,3,5].map(i=>parseInt(h.slice(i,i+2),16)/255).map(x=>x<=.03928?x/12.92:((x+.055)/1.055)**2.4);return .2126*x[0]+.7152*x[1]+.0722*x[2]};const a=lum(d.querySelector('#a').value),bb=lum(d.querySelector('#b').value),r=(Math.max(a,bb)+.05)/(Math.min(a,bb)+.05);d.querySelector('#o').textContent=`Contrast ratio: ${r.toFixed(2)}:1`};return d});
add('Design','svgpng','🖼️','SVG to PNG','Convert SVG markup to a PNG image.',b=>{const d=fields(`<textarea id="i" rows="12" placeholder="<svg ...></svg>"></textarea><button class="btn" id="go">Convert</button>`);d.querySelector('#go').onclick=async()=>{const blob=new Blob([d.querySelector('#i').value],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),im=await imageLoad(new File([blob],'x.svg',{type:'image/svg+xml'})),c=document.createElement('canvas');c.width=im.naturalWidth||800;c.height=im.naturalHeight||600;c.getContext('2d').drawImage(im,0,0);dl(await canvasBlob(c,'image/png'),'converted.png');URL.revokeObjectURL(url)};return d});

// More Study
add('Study','pomodoro','🍅','Pomodoro Timer','25/5 focus timer with short breaks.',b=>{const d=fields(`<div id="o" class="big">25:00</div><div class="actions"><button class="btn" id="s">Start</button><button class="btn secondary" id="r">Reset</button></div>`);let t,n=25*60,focus=true;const draw=()=>d.querySelector('#o').textContent=`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;d.querySelector('#s').onclick=()=>{clearInterval(t);t=setInterval(()=>{n--;draw();if(n<=0){clearInterval(t);focus=!focus;n=(focus?25:5)*60;alert(focus?'Focus time!':'Break time!')}},1000)};d.querySelector('#r').onclick=()=>{clearInterval(t);focus=true;n=1500;draw()};return d});
add('Study','randompicker','🎯','Random Picker','Pick one item from a list at random.',b=>{const d=fields(`<textarea id="i" rows="10" placeholder="One option per line"></textarea><button class="btn" id="go">Pick</button><div id="o" class="big"></div>`);d.querySelector('#go').onclick=()=>{const a=d.querySelector('#i').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);d.querySelector('#o').textContent=a.length?a[Math.floor(Math.random()*a.length)]:'Add options first'};return d});

// More Games
add('Games','snake','🐍','Snake','Classic snake game running entirely in the browser.',b=>{const d=fields(`<canvas id="c" width="320" height="320" style="max-width:100%;border:1px solid #ccc"></canvas><div class="out" id="o">Use arrow keys. Press Start.</div><button class="btn" id="s">Start</button>`);const c=d.querySelector('#c'),x=c.getContext('2d');let snake,food,dir,run,score;const place=()=>food={x:Math.floor(Math.random()*20),y:Math.floor(Math.random()*20)};const draw=()=>{x.clearRect(0,0,320,320);x.fillText('🍎',food.x*16+2,food.y*16+14);snake.forEach(p=>{x.fillRect(p.x*16,p.y*16,15,15)})};d.querySelector('#s').onclick=()=>{snake=[{x:10,y:10}];dir={x:1,y:0};score=0;place();clearInterval(run);run=setInterval(()=>{const h={x:snake[0].x+dir.x,y:snake[0].y+dir.y};if(h.x<0||h.y<0||h.x>=20||h.y>=20||snake.some(p=>p.x===h.x&&p.y===h.y)){clearInterval(run);return}snake.unshift(h);if(h.x===food.x&&h.y===food.y){score++;place()}else snake.pop();draw();d.querySelector('#o').textContent='Score: '+score},120);draw()};window.addEventListener('keydown',e=>{if(!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))return;const m={ArrowUp:{x:0,y:-1},ArrowDown:{x:0,y:1},ArrowLeft:{x:-1,y:0},ArrowRight:{x:1,y:0}}[e.key];if(dir&&m.x!==-dir.x&&m.y!==-dir.y)dir=m});return d});
add('Games','2048','🔢','2048 Mini','A compact 2048-style number game.',b=>{const d=fields(`<div id="g" style="display:grid;grid-template-columns:repeat(4,1fr);gap:5px"></div><div id="o" class="out">Use arrow keys.</div>`);let a=Array(16).fill(0);const spawn=()=>{const z=a.map((v,i)=>v?null:i).filter(v=>v!==null);if(z.length)a[z[Math.floor(Math.random()*z.length)]]=2};const draw=()=>d.querySelector('#g').innerHTML=a.map(v=>`<div style="padding:20px;text-align:center;border:1px solid #ccc">${v||''}</div>`).join('');const move=()=>{for(let r=0;r<4;r++){let row=a.slice(r*4,r*4+4).filter(Boolean);for(let i=0;i<row.length-1;i++)if(row[i]===row[i+1]){row[i]*=2;row.splice(i+1,1)};row=[...row,...Array(4-row.length).fill(0)];a.splice(r*4,4,...row)}spawn();draw()};spawn();spawn();draw();window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){for(let r=0;r<4;r++){let row=a.slice(r*4,r*4+4);if(e.key==='ArrowRight')row.reverse();let old=row.join(),tmp=row.filter(Boolean);for(let i=0;i<tmp.length-1;i++)if(tmp[i]===tmp[i+1]){tmp[i]*=2;tmp.splice(i+1,1)};row=[...tmp,...Array(4-tmp.length).fill(0)];if(e.key==='ArrowRight')row.reverse();a.splice(r*4,4,...row)}spawn();draw()}else if(['ArrowUp','ArrowDown'].includes(e.key)){const cols=[];for(let c=0;c<4;c++)cols.push([0,1,2,3].map(r=>a[r*4+c]));cols.forEach((col,c)=>{if(e.key==='ArrowDown')col.reverse();let tmp=col.filter(Boolean);for(let i=0;i<tmp.length-1;i++)if(tmp[i]===tmp[i+1]){tmp[i]*=2;tmp.splice(i+1,1)};col=[...tmp,...Array(4-tmp.length).fill(0)];if(e.key==='ArrowDown')col.reverse();col.forEach((v,r)=>a[r*4+c]=v)});spawn();draw()}});return d});

// Device utilities
add('Games','typing','⌨️','Typing Speed Test','Measure typing speed on a sample sentence.',b=>{const d=fields(`<p id="q">The quick brown fox jumps over the lazy dog.</p><textarea id="i" rows="4"></textarea><button class="btn" id="go">Check</button><div id="o" class="out"></div>`);const start=performance.now();d.querySelector('#go').onclick=()=>{const sec=(performance.now()-start)/60000,txt=d.querySelector('#i').value,wpm=Math.round((txt.trim().split(/\s+/).filter(Boolean).length)/sec);d.querySelector('#o').textContent=`Approx. ${wpm} WPM`};return d});
add('Developer','screen','🖥️','Screen Recorder','Record your screen using browser permission.',b=>{const d=fields(`<button class="btn" id="s">Start</button><button class="btn secondary" id="x">Stop</button><div id="o" class="out"></div>`);let r,ch=[];d.querySelector('#s').onclick=async()=>{const st=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});r=new MediaRecorder(st);ch=[];r.ondataavailable=e=>ch.push(e.data);r.onstop=()=>{st.getTracks().forEach(t=>t.stop());const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(ch,{type:'video/webm'}));a.download='screen-recording.webm';a.textContent='Download recording';d.querySelector('#o').replaceChildren(a)};r.start()};d.querySelector('#x').onclick=()=>r?.stop();return d});
add('Developer','webcam','📷','Webcam Recorder','Preview and record webcam video locally.',b=>{const d=fields(`<video id="v" autoplay muted playsinline style="max-width:100%"></video><div class="actions"><button class="btn" id="s">Start</button><button class="btn secondary" id="x">Stop</button></div><div id="o" class="out"></div>`);let st,r,ch=[];d.querySelector('#s').onclick=async()=>{st=await navigator.mediaDevices.getUserMedia({video:true,audio:true});d.querySelector('#v').srcObject=st;r=new MediaRecorder(st);ch=[];r.ondataavailable=e=>ch.push(e.data);r.onstop=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(ch,{type:'video/webm'}));a.download='webcam.webm';a.textContent='Download webcam video';d.querySelector('#o').replaceChildren(a)};r.start()};d.querySelector('#x').onclick=()=>{r?.stop();st?.getTracks().forEach(t=>t.stop())};return d});

function render(){const q=$('#search').value.toLowerCase(),c=$('#cat').value;const box=$('#cards');box.innerHTML='';tools.filter(t=>(c==='all'||t.cat===c)&&(!q||(t.title+' '+t.desc+' '+t.cat).toLowerCase().includes(q))).forEach(t=>{const el=document.createElement('article');el.className='card';el.innerHTML=`<div class=icon>${t.icon}</div><h3>${t.title}</h3><p>${t.desc}</p><span class=tag>${t.cat}</span>`;el.onclick=()=>openTool(t);box.append(el)})}
function openTool(t){$('#cards').classList.add('hidden');$('.toolbar').classList.add('hidden');$('.hero').classList.add('hidden');$('#work').classList.remove('hidden');$('#wIcon').textContent=t.icon;$('#wTitle').textContent=t.title;$('#wDesc').textContent=t.desc;const b=$('#toolBody');b.innerHTML='';try{const x=t.render(b);if(x)b.append(x)}catch(e){b.innerHTML=`<div class=out>${esc(e.message)}</div>`}}
$('#back').onclick=()=>{$('#work').classList.add('hidden');$('#cards').classList.remove('hidden');$('.toolbar').classList.remove('hidden');$('.hero').classList.remove('hidden')};$('#search').oninput=render;$('#cat').onchange=render;$('#menuBtn').onclick=()=>$('#menu').classList.toggle('hidden');cats.forEach(c=>$('#cat').insertAdjacentHTML('beforeend',`<option>${c}</option>`));render();
