(()=>{
 if(typeof add!=='function')return;
 const B=fields, base=(p)=>p.replace(/\.[^.]+$/,'');
 function loadScript(src){return new Promise((res,rej)=>{if(document.querySelector(`script[src="${src}"]`))return res();const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
 // 4 Generic file compressor: ZIP is deterministic and lossless; it never pretends to recompress arbitrary binary data.
 add('Data','file-compressor','🗜️','File Compressor','Bundle files into a ZIP archive locally.',()=>{const d=B(`<input id="f" type="file" multiple><button class="btn" id="go">Compress to ZIP</button><div id="o" class="out"></div>`);d.querySelector('#go').onclick=async()=>{try{await loadScript('../pdf-tool/libs/jszip.min.js');const z=new JSZip();const fs=[...d.querySelector('#f').files];if(!fs.length){d.querySelector('#o').textContent='Select files first.';return}for(const f of fs)z.file(f.name,f);const blob=await z.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}});dl(blob,'compressed-files.zip');d.querySelector('#o').textContent=`Compressed ${fs.length} file(s).`}catch(e){d.querySelector('#o').textContent='Compression failed: '+e.message}};return d});
 // 6 OCR
 add('Image','ocr','📑','OCR — Image → Text','Extract text from an image using Tesseract.js in the browser.',()=>{const d=B(`<input id="f" type="file" accept="image/*"><select id="l"><option value="eng">English</option><option value="hin">Hindi</option></select><button class="btn" id="go">Run OCR</button><div class="out" id="o">OCR downloads the selected language model on first use.</div>`);d.querySelector('#go').onclick=async()=>{const f=d.querySelector('#f').files[0];if(!f)return;try{await loadScript('https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js');const r=await Tesseract.recognize(f,d.querySelector('#l').value,{logger:m=>{if(m.progress)d.querySelector('#o').textContent=`OCR: ${m.status||'working'} ${Math.round(m.progress*100)}%`}});d.querySelector('#o').textContent=r.data.text.trim()||'No text detected.'}catch(e){d.querySelector('#o').textContent='OCR failed: '+e.message}};return d});
 // 7 PDF signature: uses the local pdf-lib already in the project.
 add('Design','pdf-sign','✍️','PDF e-Sign / Signature','Draw a signature and place it on page 1 of a PDF.',()=>{const d=B(`<input id="f" type="file" accept="application/pdf"><canvas id="c" width="600" height="180" style="max-width:100%;border:1px solid #ccc;background:white;touch-action:none"></canvas><button class="btn secondary" id="clear">Clear</button><button class="btn" id="go">Sign PDF</button><div id="o" class="out"></div>`);const c=d.querySelector('#c'),x=c.getContext('2d');let down=false,last=null;c.addEventListener('pointerdown',e=>{down=true;last=[e.offsetX,e.offsetY]});c.addEventListener('pointerup',()=>{down=false;last=null});c.addEventListener('pointerleave',()=>{down=false});c.addEventListener('pointermove',e=>{if(!down)return;x.beginPath();x.moveTo(...last);x.lineTo(e.offsetX,e.offsetY);x.strokeStyle='#111';x.lineWidth=3;x.lineCap='round';x.stroke();last=[e.offsetX,e.offsetY]});d.querySelector('#clear').onclick=()=>x.clearRect(0,0,c.width,c.height);d.querySelector('#go').onclick=async()=>{try{const f=d.querySelector('#f').files[0];if(!f)throw Error('Select a PDF.');await loadScript('../pdf-tool/libs/pdf-lib.min.js');const pdf=await PDFLib.PDFDocument.load(await f.arrayBuffer());const page=pdf.getPages()[0];const png=await pdf.embedPng(c.toDataURL('image/png'));const w=Math.min(180,page.getWidth()/3),h=w*c.height/c.width;page.drawImage(png,{x:30,y:30,width:w,height:h});dl(new Blob([await pdf.save()],{type:'application/pdf'}),base(f.name)+'-signed.pdf');d.querySelector('#o').textContent='Signed PDF created.'}catch(e){d.querySelector('#o').textContent='Signing failed: '+e.message}};return d});
 // 9 Duplicate file finder
 add('Security','duplicates','🔍','Duplicate File Finder','Find duplicate files by SHA-256 hash.',()=>{const d=B(`<input id="f" type="file" multiple><button class="btn" id="go">Find Duplicates</button><div id="o" class="out"></div>`);d.querySelector('#go').onclick=async()=>{const fs=[...d.querySelector('#f').files];const map=new Map();for(const f of fs){const h=await crypto.subtle.digest('SHA-256',await f.arrayBuffer()),k=[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('');if(!map.has(k))map.set(k,[]);map.get(k).push(f.name)}const dup=[...map.values()].filter(a=>a.length>1);d.querySelector('#o').textContent=dup.length?dup.map(a=>'Duplicate group:\n• '+a.join('\n• ')).join('\n\n'):'No duplicates found.'};return d});
 // 10 Metadata remover: image re-encode plus PDF save normalization.
 add('Security','metadata','🧹','Metadata Remover','Strip common image metadata by re-encoding; PDF save can normalize document metadata.',()=>{const d=B(`<input id="f" type="file" accept="image/*,application/pdf"><button class="btn" id="go">Remove Metadata</button><div id="o" class="out"></div>`);d.querySelector('#go').onclick=async()=>{const f=d.querySelector('#f').files[0];if(!f)return;try{if(f.type.startsWith('image/')){const im=await imageLoad(f),c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;c.getContext('2d').drawImage(im,0,0);dl(await canvasBlob(c,'image/png'),'metadata-stripped.png')}else if(f.type==='application/pdf'){await loadScript('../pdf-tool/libs/pdf-lib.min.js');const pdf=await PDFLib.PDFDocument.load(await f.arrayBuffer());pdf.setTitle('');pdf.setAuthor('');pdf.setSubject('');pdf.setKeywords([]);pdf.setCreator('');pdf.setProducer('');dl(new Blob([await pdf.save()],{type:'application/pdf'}),'metadata-stripped.pdf')}else throw Error('Unsupported file type');d.querySelector('#o').textContent='Metadata removal/export complete.'}catch(e){d.querySelector('#o').textContent='Failed: '+e.message}};return d});
 // 11 ZIP / UnZIP
 add('Data','zip-unzip','📦','ZIP / UnZIP Tools','Create ZIP archives or extract ZIP files in the browser.',()=>{const d=B(`<div class="grid2"><div><input id="z" type="file" multiple><button class="btn" id="zip">Create ZIP</button></div><div><input id="u" type="file" accept=".zip"><button class="btn" id="unzip">Extract ZIP</button></div></div><div id="o" class="out"></div>`);d.querySelector('#zip').onclick=async()=>{try{await loadScript('../pdf-tool/libs/jszip.min.js');const z=new JSZip(),fs=[...d.querySelector('#z').files];for(const f of fs)z.file(f.name,f);dl(await z.generateAsync({type:'blob'}),'archive.zip');d.querySelector('#o').textContent='ZIP created.'}catch(e){d.querySelector('#o').textContent=e.message}};d.querySelector('#unzip').onclick=async()=>{try{await loadScript('../pdf-tool/libs/jszip.min.js');const f=d.querySelector('#u').files[0];if(!f)return;const z=await JSZip.loadAsync(f);const files=Object.values(z.files).filter(x=>!x.dir);for(const entry of files){const blob=await entry.async('blob');dl(blob,entry.name)}d.querySelector('#o').textContent=`Extracted ${files.length} file(s). Downloads may be prompted individually.`}catch(e){d.querySelector('#o').textContent='UnZIP failed: '+e.message}};return d});
 // Processing mini-game
 add('Games','processing-game','🎮','Processing Game','Play a tiny reaction game while a demo task runs.',()=>{const d=B(`<div class="game" id="g"><button class="target" id="t">🎯</button></div><div class="out" id="o">Hit the target. Start a 15-second session.</div><button class="btn" id="s">Start</button>`);let timer,score=0;const g=d.querySelector('#g'),t=d.querySelector('#t'),o=d.querySelector('#o');const move=()=>{t.style.left=Math.random()*85+'%';t.style.top=Math.random()*75+'%'};t.onclick=()=>{score++;o.textContent=`Score: ${score}`;move()};d.querySelector('#s').onclick=()=>{clearInterval(timer);score=0;move();let end=Date.now()+15000;timer=setInterval(()=>{const left=Math.max(0,end-Date.now());o.textContent=`Processing demo… ${Math.ceil(left/1000)}s • Score: ${score}`;if(!left){clearInterval(timer);o.textContent=`Done! Final score: ${score}`}},250)};move();return d});
})();
