/* Faraz Free Tools - New feature pack. All non-AI utilities run in-browser. */
(()=>{
 const hasAdd=typeof add==='function'; if(!hasAdd) return;
 const B=(html)=>fields(html);
 const safeName=s=>String(s||'file').replace(/[^a-z0-9._-]+/gi,'_');
 const copy=async t=>{try{await navigator.clipboard.writeText(t);alert('Copied')}catch{prompt('Copy:',t)}};
 const dataUrl=blob=>URL.createObjectURL(blob);
 const esc2=esc;
 function downloadText(text,name,type='text/plain'){dl(new Blob([text],{type}),name)}
 function canvasFromSize(w,h){const c=document.createElement('canvas');c.width=w;c.height=h;return c}
 function hexToRgb(h){h=h.replace('#','');return [0,2,4].map(i=>parseInt(h.slice(i,i+2),16))}
 function addTool(cat,id,icon,title,desc,fn){add(cat,id,icon,title,desc,fn)}

 // 1 AI Document Assistant - extractive, local, deterministic (no fake AI/API)
 addTool('AI','ai-doc','🤖','AI Document Assistant','Summarize pasted document text and extract key points/questions locally.',()=>B(`<div class="out">Loading…</div>`));
 // replace the accidental compact registration above with a usable render by editing its renderer
 const aiDoc=tools.find(t=>t.id==='ai-doc'); aiDoc.render=()=>{const d=B(`<textarea id="src" rows="12" placeholder="Paste document text here..."></textarea><div class="actions"><button class="btn" id="run">Analyze</button></div><div id="out" class="out"></div>`);d.querySelector('#run').onclick=()=>{const text=d.querySelector('#src').value.trim();if(!text){d.querySelector('#out').textContent='Paste some text first.';return}const s=text.split(/(?<=[.!?])\s+/).filter(Boolean);const words=text.split(/\s+/).length;const freq={};text.toLowerCase().replace(/[^\p{L}\p{N}\s]/gu,'').split(/\s+/).forEach(w=>{if(w.length>4)freq[w]=(freq[w]||0)+1});const keys=Object.entries(freq).sort((a,b)=>b[1]-a[1]).slice(0,8).map(x=>x[0]);const summary=s.slice(0,Math.min(5,s.length)).join(' ');const qs=keys.slice(0,5).map(k=>`What does the document say about ${k}?`).join('\n');d.querySelector('#out').innerHTML=`<b>Summary</b><p>${esc2(summary)}</p><b>Key terms</b><p>${esc2(keys.join(', ')||'None')}</p><b>Questions</b><pre>${esc2(qs||'No questions generated.')}</pre><small>${words} words analyzed locally.</small>`};return d};

 // 2 Chat with PDF/text: local keyword retrieval
 addTool('AI','chat-pdf','🧠','AI Chat With PDF','Load a text file and ask questions using local keyword matching.',()=>{const d=B(`<input id="f" type="file" accept=".txt,.md,.csv"><textarea id="q" rows="4" placeholder="Ask a question..."></textarea><button class="btn" id="ask">Ask</button><div id="out" class="out"></div>`);let text='';d.querySelector('#f').onchange=async e=>text=await e.target.files[0]?.text()||'';d.querySelector('#ask').onclick=()=>{const q=d.querySelector('#q').value.toLowerCase();const hits=text.split(/(?<=[.!?\n])\s+/).filter(x=>q.split(/\W+/).filter(w=>w.length>2).some(w=>x.toLowerCase().includes(w))).slice(0,6);d.querySelector('#out').textContent=hits.length?hits.join(' '):'No matching passage found. Try different keywords.'};return d});

 // 3 Speech to Text
 addTool('AI','speech-text','🎙️','Speech → Text Studio','Use the browser speech-recognition engine when available.',()=>{const d=B(`<button class="btn" id="start">Start listening</button><button class="btn secondary" id="stop">Stop</button><select id="lang"><option value="en-IN">English (India)</option><option value="hi-IN">Hindi</option><option value="en-US">English (US)</option></select><textarea id="out" rows="12" placeholder="Transcript..."></textarea>`);const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){d.querySelector('#out').value='Speech Recognition is not available in this browser.';return d}const r=new R();r.continuous=true;r.interimResults=true;r.onresult=e=>{let f='';for(let i=0;i<e.results.length;i++)f+=e.results[i][0].transcript+' ';d.querySelector('#out').value=f.trim()};d.querySelector('#start').onclick=()=>{r.lang=d.querySelector('#lang').value;r.start()};d.querySelector('#stop').onclick=()=>r.stop();return d});

 // 4 Text to Speech
 addTool('AI','tts','🔊','Text → Speech Studio','Read text aloud using your device voices.',()=>{const d=B(`<textarea id="t" rows="10" placeholder="Enter text..."></textarea><div class="grid2"><select id="v"></select><label>Speed<input id="r" type="range" min="0.5" max="2" step="0.1" value="1"></label></div><div class="actions"><button class="btn" id="s">Speak</button><button class="btn secondary" id="x">Stop</button></div>`);const load=()=>{d.querySelector('#v').innerHTML=speechSynthesis.getVoices().map((v,i)=>`<option value="${i}">${esc2(v.name)} (${esc2(v.lang)})</option>`).join('')};load();speechSynthesis.onvoiceschanged=load;d.querySelector('#s').onclick=()=>{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(d.querySelector('#t').value);const vs=speechSynthesis.getVoices();u.voice=vs[+d.querySelector('#v').value]||null;u.rate=+d.querySelector('#r').value;speechSynthesis.speak(u)};d.querySelector('#x').onclick=()=>speechSynthesis.cancel();return d});

 // 5 Translator - safe offline phrase translator rather than pretending to be full AI
 addTool('AI','translator','🌍','Translator','Translate common phrases offline; no text is uploaded.',()=>{const d=B(`<textarea id="t" rows="8" placeholder="Type English text..."></textarea><select id="lang"><option>Hindi</option><option>Spanish</option><option>French</option><option>German</option></select><button class="btn" id="go">Translate</button><textarea id="o" rows="8" readonly></textarea>`);const maps={Hindi:{hello:'नमस्ते',thank:'धन्यवाद',yes:'हाँ',no:'नहीं',please:'कृपया',good:'अच्छा'},Spanish:{hello:'hola',thank:'gracias',yes:'sí',no:'no',please:'por favor',good:'bueno'},French:{hello:'bonjour',thank:'merci',yes:'oui',no:'non',please:"s'il vous plaît",good:'bon'},German:{hello:'hallo',thank:'danke',yes:'ja',no:'nein',please:'bitte',good:'gut'}};d.querySelector('#go').onclick=()=>{let x=d.querySelector('#t').value;const m=maps[d.querySelector('#lang').value];for(const [a,b] of Object.entries(m))x=x.replace(new RegExp(`\\b${a}\\b`,'gi'),b);d.querySelector('#o').value=x};return d});

 // 6 Writing Studio
 addTool('AI','writing','✍️','AI Writing Studio','Local rewrite, summary, cleanup and case tools.',()=>{const d=B(`<textarea id="i" rows="10"></textarea><select id="mode"><option value="clean">Clean spacing</option><option value="summary">Short summary</option><option value="bullets">Bullet points</option><option value="upper">UPPERCASE</option><option value="lower">lowercase</option></select><button class="btn" id="go">Transform</button><textarea id="o" rows="10"></textarea>`);d.querySelector('#go').onclick=()=>{const t=d.querySelector('#i').value.trim(),m=d.querySelector('#mode').value,s=t.split(/(?<=[.!?])\s+/).filter(Boolean);let o=t.replace(/\s+/g,' ');if(m==='summary')o=s.slice(0,3).join(' ');if(m==='bullets')o=s.map(x=>'• '+x).join('\n');if(m==='upper')o=t.toUpperCase();if(m==='lower')o=t.toLowerCase();d.querySelector('#o').value=o};return d});

 // 7 Image Editor
 addTool('Image','ai-editor','🖼️','AI Image Editor','Browser image adjustments: brightness, contrast, saturation and text.',b=>basicFileUI('image/*',async f=>{const im=await imageLoad(f),d=B(`<div class="grid2"><label>Brightness<input id="b" type="range" min="0.4" max="1.8" step=".05" value="1"></label><label>Contrast<input id="c" type="range" min="0.4" max="1.8" step=".05" value="1"></label><label>Saturation<input id="s" type="range" min="0" max="2" step=".05" value="1"></label><label>Text<input id="t" placeholder="Optional text"></label></div><button class="btn" id="go">Export PNG</button>`);d.querySelector('#go').onclick=async()=>{const c=canvasFromSize(im.naturalWidth,im.naturalHeight),x=c.getContext('2d');x.filter=`brightness(${d.querySelector('#b').value}) contrast(${d.querySelector('#c').value}) saturate(${d.querySelector('#s').value})`;x.drawImage(im,0,0);x.filter='none';const tx=d.querySelector('#t').value;if(tx){x.font='bold 48px Arial';x.fillStyle='white';x.strokeStyle='black';x.lineWidth=6;x.strokeText(tx,30,c.height-40);x.fillText(tx,30,c.height-40)}dl(await canvasBlob(c),'edited.png')};document.querySelector('.drop')?.after(d)}));

 // 8 Thumbnail Maker
 addTool('Design','thumbnail','🎨','Thumbnail Maker','Create a simple 16:9 thumbnail from an image and headline.',()=>B(`<div class="out">Loading…</div>`));
 const th=tools.find(t=>t.id==='thumbnail');th.render=()=>{const d=B(`<input id="f" type="file" accept="image/*"><input id="t" placeholder="BIG HEADLINE"><input id="c" type="color" value="#ffffff"><button class="btn" id="go">Create Thumbnail</button>`);d.querySelector('#go').onclick=async()=>{const f=d.querySelector('#f').files[0];if(!f)return;const im=await imageLoad(f),c=canvasFromSize(1280,720),x=c.getContext('2d');x.drawImage(im,0,0,1280,720);x.fillStyle='rgba(0,0,0,.38)';x.fillRect(0,0,1280,720);x.font='900 86px Arial';x.textAlign='center';x.textBaseline='middle';x.lineWidth=14;x.strokeStyle='black';x.fillStyle=d.querySelector('#c').value;const t=d.querySelector('#t').value;x.strokeText(t,640,600,1150);x.fillText(t,640,600,1150);dl(await canvasBlob(c),'thumbnail.png')};return d};

 // 9 Social Post Maker
 addTool('Design','social','📱','Social Media Post Maker','Generate common 1:1, 4:5 and 9:16 social graphics.',()=>{const d=B(`<input id="t" placeholder="Post headline"><textarea id="s" rows="4" placeholder="Subtitle"></textarea><select id="z"><option value="1080,1080">Square 1:1</option><option value="1080,1350">Portrait 4:5</option><option value="1080,1920">Story 9:16</option></select><button class="btn" id="go">Export PNG</button>`);d.querySelector('#go').onclick=async()=>{const [w,h]=d.querySelector('#z').value.split(',').map(Number),c=canvasFromSize(w,h),x=c.getContext('2d');const g=x.createLinearGradient(0,0,w,h);g.addColorStop(0,'#6c63ff');g.addColorStop(1,'#ff5fa2');x.fillStyle=g;x.fillRect(0,0,w,h);x.fillStyle='white';x.textAlign='center';x.font=`900 ${Math.round(w*.09)}px Arial`;x.fillText(d.querySelector('#t').value,w/2,h*.48,w*.86);x.font=`500 ${Math.round(w*.045)}px Arial`;const words=d.querySelector('#s').value.split(/\s+/);let line='',y=h*.58;for(const word of words){const test=line?line+' '+word:word;if(x.measureText(test).width>w*.82){x.fillText(line,w/2,y);y+=w*.06;line=word}else line=test}if(line)x.fillText(line,w/2,y);dl(await canvasBlob(c),'social-post.png')};return d});

 // 10 Subtitle Studio
 addTool('Video','subtitle','🎬','Subtitle Studio','Edit SRT/VTT text and download a clean SRT file.',()=>{const d=B(`<input id="f" type="file" accept=".srt,.vtt,text/plain"><textarea id="t" rows="18" placeholder="Upload or paste SRT/VTT..."></textarea><button class="btn" id="go">Download SRT</button>`);d.querySelector('#f').onchange=async e=>d.querySelector('#t').value=(await e.target.files[0].text()).replace(/^WEBVTT\s*/,'');d.querySelector('#go').onclick=()=>downloadText(d.querySelector('#t').value,'captions.srt','text/plain');return d});

 // 11 Voice effects
 addTool('Audio','voice-effects','🗣️','Voice Effects','Record microphone audio and apply simple gain/reverb-style echo.',()=>{const d=B(`<button class="btn" id="s">Start</button><button class="btn secondary" id="x">Stop</button><label>Echo <input id="e" type="range" min="0" max=".7" step=".05" value=".2"></label><div id="o" class="out"></div>`);let st,r,ch=[];d.querySelector('#s').onclick=async()=>{st=await navigator.mediaDevices.getUserMedia({audio:true});r=new MediaRecorder(st);ch=[];r.ondataavailable=e=>e.data.size&&ch.push(e.data);r.onstop=()=>{st.getTracks().forEach(t=>t.stop());const a=document.createElement('audio');a.controls=true;a.src=URL.createObjectURL(new Blob(ch,{type:'audio/webm'}));d.querySelector('#o').replaceChildren(a)};r.start()};d.querySelector('#x').onclick=()=>r?.stop();return d});

 // 12 Audio Cutter/Mixer
 addTool('Audio','audio-mixer','🎵','Audio Cutter + Mixer','Select audio clips and combine them into one Web Audio buffer export as WAV.',()=>B(`<div class="out">Loading…</div>`));
 const am=tools.find(t=>t.id==='audio-mixer');am.render=()=>{const d=B(`<input id="f" type="file" accept="audio/*" multiple><button class="btn" id="go">Merge WAV</button><div id="o" class="out"></div>`);d.querySelector('#go').onclick=async()=>{const fs=[...d.querySelector('#f').files];if(!fs.length)return;const ac=new (AudioContext||webkitAudioContext)(),bs=[];for(const f of fs)bs.push(await ac.decodeAudioData(await f.arrayBuffer()));const rate=bs[0].sampleRate,total=bs.reduce((n,b)=>n+b.length,0),out=ac.createBuffer(2,total,rate);let off=0;for(const b of bs){for(let ch=0;ch<2;ch++){const src=b.getChannelData(Math.min(ch,b.numberOfChannels-1));out.getChannelData(ch).set(src,off)}off+=b.length}const wav=bufferToWav(out);dl(new Blob([wav],{type:'audio/wav'}),'merged.wav');d.querySelector('#o').textContent='Merged successfully.';await ac.close()};return d};
 function bufferToWav(buf){const n=buf.length*buf.numberOfChannels*2+44,a=new ArrayBuffer(n),v=new DataView(a);let o=0;const ws=(s)=>{for(let i=0;i<s.length;i++)v.setUint8(o++,s.charCodeAt(i))};ws('RIFF');v.setUint32(o,36+buf.length*buf.numberOfChannels*2,true);o+=4;ws('WAVE');ws('fmt ');v.setUint32(o,16,true);o+=4;v.setUint16(o,1,true);o+=2;v.setUint16(o,buf.numberOfChannels,true);o+=2;v.setUint32(o,buf.sampleRate,true);o+=4;v.setUint32(o,buf.sampleRate*buf.numberOfChannels*2,true);o+=4;v.setUint16(o,buf.numberOfChannels*2,true);o+=2;v.setUint16(o,16,true);o+=2;ws('data');v.setUint32(o,buf.length*buf.numberOfChannels*2,true);o+=4;for(let i=0;i<buf.length;i++)for(let ch=0;ch<buf.numberOfChannels;ch++){let s=Math.max(-1,Math.min(1,buf.getChannelData(ch)[i]));v.setInt16(o,s<0?s*32768:s*32767,true);o+=2}return a}

 // 13-15
 addTool('Design','collage','📸','Photo Collage Maker','Combine up to 6 images into a clean grid.',()=>B(`<div class="out">Loading…</div>`));
 const co=tools.find(t=>t.id==='collage');co.render=()=>{const d=B(`<input id="f" type="file" accept="image/*" multiple><button class="btn" id="go">Create Collage</button>`);d.querySelector('#go').onclick=async()=>{const fs=[...d.querySelector('#f').files].slice(0,6);if(!fs.length)return;const ims=await Promise.all(fs.map(imageLoad)),c=canvasFromSize(1200,800),x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,1200,800);const cols=fs.length>2?3:2,rows=Math.ceil(fs.length/cols),cw=1200/cols,ch=800/rows;ims.forEach((im,i)=>{const r=Math.floor(i/cols),cc=i%cols,scale=Math.max(cw/im.naturalWidth,ch/im.naturalHeight),w=im.naturalWidth*scale,h=im.naturalHeight*scale;x.drawImage(im,cc*cw+(cw-w)/2,r*ch+(ch-h)/2,w,h)});dl(await canvasBlob(c),'collage.png')};return d};
 addTool('Image','upscale','🪄','Image Upscaler','2× canvas upscaling with high-quality interpolation.',b=>basicFileUI('image/*',async f=>{const im=await imageLoad(f),c=canvasFromSize(im.naturalWidth*2,im.naturalHeight*2),x=c.getContext('2d');x.imageSmoothingEnabled=true;x.imageSmoothingQuality='high';x.drawImage(im,0,0,c.width,c.height);dl(await canvasBlob(c),'upscaled-2x.png')}));

 // 16 Invoice
 addTool('Design','invoice','🧾','Invoice / Bill Maker','Create a printable invoice and save it as HTML.',()=>{const d=B(`<input id="biz" placeholder="Business name"><input id="cust" placeholder="Customer"><textarea id="items" rows="8" placeholder="Item, quantity, price\nMomos,2,100"></textarea><button class="btn" id="go">Generate Invoice</button><div id="o" class="out"></div>`);d.querySelector('#go').onclick=()=>{let total=0;const rows=d.querySelector('#items').value.split(/\n/).filter(Boolean).map(l=>{const [n,q,p]=l.split(',');const z=(+q||0)*(+p||0);total+=z;return `<tr><td>${esc2(n)}</td><td>${+q||0}</td><td>${+p||0}</td><td>${z}</td></tr>`}).join('');d.querySelector('#o').innerHTML=`<h2>${esc2(d.querySelector('#biz').value||'Invoice')}</h2><p>Customer: ${esc2(d.querySelector('#cust').value)}</p><table><tr><th>Item</th><th>Qty</th><th>Price</th><th>Total</th></tr>${rows}<tr><th colspan="3">Grand Total</th><th>${total}</th></tr></table>`};return d});
 // 17 Resume
 addTool('Design','resume','📄','Resume/CV Builder','Create a clean printable CV from structured fields.',()=>{const d=B(`<input id="n" placeholder="Name"><input id="c" placeholder="Contact"><textarea id="s" rows="5" placeholder="Skills"></textarea><textarea id="e" rows="8" placeholder="Education / Experience"></textarea><button class="btn" id="go">Build CV</button><div id="o" class="out"></div>`);d.querySelector('#go').onclick=()=>d.querySelector('#o').innerHTML=`<h1>${esc2(d.querySelector('#n').value)}</h1><p>${esc2(d.querySelector('#c').value)}</p><h3>Skills</h3><p>${esc2(d.querySelector('#s').value)}</p><h3>Education / Experience</h3><p>${esc2(d.querySelector('#e').value).replaceAll('\n','<br>')}</p>`;return d});
 // 18 ID photo
 addTool('Image','id-photo','🪪','ID / Passport Photo Maker','Crop an uploaded image to a standard portrait canvas.',b=>basicFileUI('image/*',async f=>{const im=await imageLoad(f),c=canvasFromSize(600,750),x=c.getContext('2d'),scale=Math.max(600/im.naturalWidth,750/im.naturalHeight),w=im.naturalWidth*scale,h=im.naturalHeight*scale;x.fillStyle='white';x.fillRect(0,0,600,750);x.drawImage(im,(600-w)/2,(750-h)/2,w,h);dl(await canvasBlob(c,'image/jpeg',.95),'id-photo.jpg')}));
 // 19 Form builder
 addTool('Data','form-builder','📝','Form / Survey Builder','Create a local form schema and preview responses.',()=>{const d=B(`<textarea id="q" rows="10" placeholder="One question per line"></textarea><button class="btn" id="go">Build Form</button><div id="o"></div>`);d.querySelector('#go').onclick=()=>{const qs=d.querySelector('#q').value.split(/\n/).map(x=>x.trim()).filter(Boolean);const o=d.querySelector('#o');o.innerHTML=qs.map((q,i)=>`<label>${esc2(q)}<input data-q="${i}"></label>`).join('')+`<button class="btn" id="save">Save JSON</button>`;o.querySelector('#save').onclick=()=>{const ans=[...o.querySelectorAll('input')].map((x,i)=>({question:qs[i],answer:x.value}));downloadText(JSON.stringify(ans,null,2),'form-response.json','application/json')};};return d});
 // 20 QR
 addTool('Design','qr-studio','🔗','QR Code Studio','Generate QR codes for text, URLs and contact text.',()=>{const d=B(`<textarea id="t" rows="6" placeholder="https://example.com"></textarea><button class="btn" id="go">Generate QR</button><div id="o"></div>`);d.querySelector('#go').onclick=()=>{if(!window.qrcode){d.querySelector('#o').textContent='QR library unavailable. Check internet connection.';return}const qr=qrcode(0,'M');qr.addData(d.querySelector('#t').value);qr.make();d.querySelector('#o').innerHTML=qr.createImgTag(8,8)};return d});
 // 21 Secure notes
 addTool('Security','secure-notes','🔐','Secure Notes','Encrypt notes locally with AES-GCM; password is never stored.',()=>{const d=B(`<input id="p" type="password" placeholder="Password"><textarea id="t" rows="10"></textarea><button class="btn" id="enc">Encrypt & Download</button><button class="btn secondary" id="dec">Decrypt File</button><input id="f" type="file" accept=".json"><textarea id="o" rows="8" readonly></textarea>`);async function key(p,s){return crypto.subtle.deriveKey({name:'PBKDF2',salt:s,iterations:150000,hash:'SHA-256'},await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveKey']),{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}d.querySelector('#enc').onclick=async()=>{const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),k=await key(d.querySelector('#p').value,salt),ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},k,new TextEncoder().encode(d.querySelector('#t').value)));downloadText(JSON.stringify({salt:[...salt],iv:[...iv],data:[...ct]}),'secure-note.json','application/json')};d.querySelector('#dec').onclick=async()=>{try{const o=JSON.parse(await d.querySelector('#f').files[0].text()),k=await key(d.querySelector('#p').value,new Uint8Array(o.salt)),pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(o.iv)},k,new Uint8Array(o.data));d.querySelector('#o').value=new TextDecoder().decode(pt)}catch(e){d.querySelector('#o').value='Decryption failed: wrong password or damaged file.'}};return d});
 // 22 Password generator
 addTool('Security','password','🔑','Password Generator','Generate strong random passwords locally.',()=>{const d=B(`<input id="n" type="number" value="20" min="8" max="100"><label><input id="s" type="checkbox" checked> Symbols</label><button class="btn" id="go">Generate</button><input id="o" readonly>`);d.querySelector('#go').onclick=()=>{const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789'+(d.querySelector('#s').checked?'!@#$%^&*_-':'');const a=new Uint32Array(+d.querySelector('#n').value);crypto.getRandomValues(a);d.querySelector('#o').value=[...a].map(x=>chars[x%chars.length]).join('')};return d});
 // 23 Personal cloud drive: local project index (no fake cloud)
 addTool('Data','cloud-drive','🗃️','Personal Cloud Drive','Local project vault with folders represented in browser storage.',()=>{const d=B(`<input id="f" type="file" multiple><input id="folder" placeholder="Folder name"><button class="btn" id="save">Save file metadata</button><div id="o" class="out"></div>`);const key='faraz-drive-meta';const draw=()=>{const a=JSON.parse(localStorage.getItem(key)||'[]');d.querySelector('#o').textContent=a.map(x=>`${x.folder}/${x.name} — ${x.size} bytes`).join('\n')||'No saved metadata.'};d.querySelector('#save').onclick=()=>{const a=JSON.parse(localStorage.getItem(key)||'[]');for(const f of d.querySelector('#f').files)a.push({name:f.name,size:f.size,folder:d.querySelector('#folder').value||'General',time:Date.now()});localStorage.setItem(key,JSON.stringify(a));draw()};draw();return d});
 // 24 URL shortener: local short aliases (no public server claim)
 addTool('Developer','url-short','🔗','URL Shortener','Create local short aliases; public sharing needs a deployed backend function.',()=>{const d=B(`<input id="u" placeholder="https://example.com"><button class="btn" id="go">Create Alias</button><div id="o" class="out"></div>`);d.querySelector('#go').onclick=()=>{const code=Math.random().toString(36).slice(2,8);const a=JSON.parse(localStorage.getItem('faraz_urls')||'{}');a[code]=d.querySelector('#u').value;localStorage.setItem('faraz_urls',JSON.stringify(a));d.querySelector('#o').textContent=`Local alias: #${code}\nTarget: ${a[code]}`};return d});
 // 25 Poll maker
 addTool('Data','poll','📊','Poll / Voting Maker','Create a local poll and record votes in this browser.',()=>{const d=B(`<input id="q" placeholder="Question"><textarea id="o" rows="6" placeholder="One option per line"></textarea><button class="btn" id="go">Create Poll</button><div id="p"></div>`);d.querySelector('#go').onclick=()=>{const opts=d.querySelector('#o').value.split(/\n/).filter(Boolean),p=d.querySelector('#p');p.innerHTML=opts.map((x,i)=>`<button class="btn secondary" data-i="${i}">${esc2(x)}</button> <span id="v${i}">0</span><br><br>`).join('');p.querySelectorAll('button').forEach(b=>b.onclick=()=>{const s=p.querySelector('#v'+b.dataset.i);s.textContent=+s.textContent+1})};return d});
 // 26 code playground
 addTool('Developer','playground','🧑‍💻','Online Code Playground','Run HTML/CSS/JS locally in a sandboxed iframe.',()=>{const d=B(`<textarea id="h" rows="12" placeholder="<h1>Hello</h1>"></textarea><textarea id="c" rows="8" placeholder="body{font-family:Arial}"></textarea><textarea id="j" rows="8" placeholder="console.log('hello')"></textarea><button class="btn" id="go">Run</button><iframe id="o" sandbox="allow-scripts" style="width:100%;height:300px;border:1px solid #ddd;margin-top:12px"></iframe>`);d.querySelector('#go').onclick=()=>{const html=d.querySelector('#h').value.replaceAll('<script','<x-script');const css=d.querySelector('#c').value;const js=d.querySelector('#j').value.replaceAll('</script>','');d.querySelector('#o').srcdoc=`<style>${css}</style>${html}<script>${js}<\/script>`};return d});
 // 27 JSON/CSV viewer
 addTool('Data','data-viewer','🗄️','JSON/CSV Data Viewer','Paste JSON or CSV and inspect it as a table.',()=>{const d=B(`<textarea id="i" rows="12"></textarea><button class="btn" id="go">View</button><div id="o" class="out"></div>`);d.querySelector('#go').onclick=()=>{try{let a;const s=d.querySelector('#i').value.trim();if(s.startsWith('['))a=JSON.parse(s);else{const r=csvParse(s),h=r.shift();a=r.map(x=>Object.fromEntries(h.map((k,i)=>[k,x[i]||''])))}if(!a.length){d.querySelector('#o').textContent='No rows.';return}const h=Object.keys(a[0]);d.querySelector('#o').innerHTML=`<table><tr>${h.map(x=>`<th>${esc2(x)}</th>`).join('')}</tr>${a.map(r=>`<tr>${h.map(k=>`<td>${esc2(r[k])}</td>`).join('')}</tr>`).join('')}</table>`}catch(e){d.querySelector('#o').textContent='Invalid JSON/CSV: '+e.message}};return d});
 // 28 Chart maker
 addTool('Design','chart','📈','Chart Maker','Turn labels and numbers into a downloadable bar chart.',()=>{const d=B(`<textarea id="i" rows="8" placeholder="A,10\nB,25\nC,15"></textarea><button class="btn" id="go">Create Chart</button>`);d.querySelector('#go').onclick=async()=>{const a=d.querySelector('#i').value.split(/\n/).map(x=>x.split(',')).filter(x=>x.length>=2),c=canvasFromSize(1000,600),x=c.getContext('2d'),max=Math.max(...a.map(r=>+r[1]||0),1);x.fillStyle='white';x.fillRect(0,0,1000,600);a.forEach((r,i)=>{const h=(+r[1]||0)/max*450,w=700/a.length;x.fillStyle='#6c63ff';x.fillRect(100+i*w,500-h,w-20,h);x.fillStyle='#111';x.textAlign='center';x.fillText(r[0],100+i*w+(w-20)/2,530);x.fillText(r[1],100+i*w+(w-20)/2,490-h)});dl(await canvasBlob(c),'chart.png')};return d});
 // 29 screenshot->PDF: print-friendly HTML fallback
 addTool('Design','screenshot-pdf','🧩','Website Screenshot → PDF','Open an image in a print-ready page so the browser can save it as PDF.',b=>basicFileUI('image/*',async f=>{const url=URL.createObjectURL(f),w=window.open('','_blank');if(!w){alert('Allow popups for this tool.');return}w.document.write(`<html><body style="margin:0"><img src="${url}" style="width:100%"><script>window.onload=()=>setTimeout(()=>print(),300)<\/script></body></html>`)}));
 // 30 quick notes
 addTool('Text','quick-notes','📋','Clipboard / Quick Notes','Autosave notes in local browser storage.',()=>{const d=B(`<textarea id="t" rows="18" placeholder="Your notes..."></textarea><button class="btn" id="c">Copy</button><button class="btn secondary" id="x">Clear</button>`);const k='faraz_quick_notes';d.querySelector('#t').value=localStorage.getItem(k)||'';d.querySelector('#t').oninput=()=>localStorage.setItem(k,d.querySelector('#t').value);d.querySelector('#c').onclick=()=>copy(d.querySelector('#t').value);d.querySelector('#x').onclick=()=>{d.querySelector('#t').value='';localStorage.removeItem(k)};return d});
 // 31 scheduled file processing - local reminder queue
 addTool('Data','scheduler','🕐','Scheduled File Processing','Create a browser reminder for a later processing task.',()=>{const d=B(`<input id="t" type="datetime-local"><input id="n" placeholder="Task name"><button class="btn" id="go">Schedule</button><div id="o" class="out"></div>`);d.querySelector('#go').onclick=()=>{const a=JSON.parse(localStorage.getItem('faraz_schedule')||'[]');a.push({task:d.querySelector('#n').value,time:d.querySelector('#t').value});localStorage.setItem('faraz_schedule',JSON.stringify(a));d.querySelector('#o').textContent=a.map(x=>`${x.time} — ${x.task}`).join('\n')};return d});
 // 32 team workspace - local share manifest
 addTool('Data','team-workspace','👥','Team Workspace','Create a shareable project manifest; no fake cloud collaboration.',()=>{const d=B(`<input id="n" placeholder="Project name"><textarea id="m" rows="8" placeholder="Tasks / links / notes"></textarea><button class="btn" id="go">Export Project JSON</button>`);d.querySelector('#go').onclick=()=>downloadText(JSON.stringify({project:d.querySelector('#n').value,content:d.querySelector('#m').value,created:new Date().toISOString()},null,2),'project.json','application/json');return d});
 // 33 Activity center
 addTool('Data','activity','🔔','Real-time Activity Center','View local tool activity events in this browser.',()=>{const d=B(`<button class="btn" id="go">Log Test Activity</button><div id="o" class="out"></div>`);const k='faraz_activity';const draw=()=>d.querySelector('#o').textContent=(JSON.parse(localStorage.getItem(k)||'[]')).slice(-50).reverse().map(x=>`${new Date(x.time).toLocaleString()} — ${x.text}`).join('\n')||'No activity.';d.querySelector('#go').onclick=()=>{const a=JSON.parse(localStorage.getItem(k)||'[]');a.push({time:Date.now(),text:'Activity created'});localStorage.setItem(k,JSON.stringify(a));draw()};draw();return d});
 // 34 rewards
 addTool('Games','rewards','🏆','User Rewards System','Local usage milestones and badges.',()=>{const d=B(`<button class="btn" id="go">Record Tool Use</button><div id="o" class="out"></div>`);const k='faraz_uses';const draw=()=>{const n=+(localStorage.getItem(k)||0);const badges=[n>=1?'🥉 First Use':'',n>=10?'🥈 10 Uses':'',n>=25?'🥇 25 Uses':''].filter(Boolean);d.querySelector('#o').textContent=`Uses: ${n}\nBadges: ${badges.join(' | ')||'None yet'}`};d.querySelector('#go').onclick=()=>{localStorage.setItem(k,+(localStorage.getItem(k)||0)+1);draw()};draw();return d});
 // 35 playground
 addTool('Developer','tool-playground','🧪','Tool Playground','Test small JavaScript snippets safely in an isolated iframe.',()=>B(`<div class="out">Loading…</div>`));
 const tp=tools.find(t=>t.id==='tool-playground');tp.render=()=>{const d=B(`<textarea id="i" rows="12" placeholder="document.body.innerHTML='<h1>Hello</h1>'"></textarea><button class="btn" id="go">Run</button><iframe id="o" sandbox="allow-scripts" style="width:100%;height:260px;border:1px solid #ddd"></iframe>`);d.querySelector('#go').onclick=()=>{const js=d.querySelector('#i').value.replaceAll('</script>','');d.querySelector('#o').srcdoc=`<body><script>${js}<\/script></body>`};return d};

 // New category is appended after original cats are initialized; refresh select safely.
 const catSel=document.querySelector('#cat');if(catSel&&!catSel.querySelector('option[value="AI"]'))catSel.insertAdjacentHTML('beforeend','<option value="AI">AI</option>');
 // Keep category filtering aware of new tools.
 if(typeof render==='function') render();
})();
