const $=s=>document.querySelector(s), videoInput=$('#videoInput'),srtInput=$('#srtInput'),video=$('#video'),editor=$('#editor'),list=$('#list'),preview=$('#previewCaption');let cues=[],selected=-1;
$('#chooseBtn').onclick=()=>videoInput.click();$('#srtBtn').onclick=()=>srtInput.click();
videoInput.onchange=()=>{const f=videoInput.files[0];if(!f)return;video.src=URL.createObjectURL(f);$('#fileName').textContent=f.name;editor.classList.remove('hidden')};
srtInput.onchange=async()=>{const f=srtInput.files[0];if(!f)return;const text=await f.text();cues=parseSubs(text);render();editor.classList.remove('hidden')};
video.ontimeupdate=()=>{const t=video.currentTime;$('#time').value=video.duration?100*t/video.duration:0;$('#now').textContent=fmt(t);$('#dur').textContent=fmt(video.duration||0);const i=cues.findIndex(c=>t>=c.start&&t<=c.end);preview.textContent=i>=0?cues[i].text:''};$('#time').oninput=()=>{if(video.duration)video.currentTime=video.duration*(+$('#time').value/100)};
$('#add').onclick=()=>{const a=+$('#start').value,e=+$('#end').value,t=$('#text').value.trim();if(!t||e<=a)return; cues.push({start:a,end:e,text:t});cues.sort((x,y)=>x.start-y.start);selected=-1;render()};$('#update').onclick=()=>{if(selected<0)return;Object.assign(cues[selected],{start:+$('#start').value,end:+$('#end').value,text:$('#text').value.trim()});cues.sort((x,y)=>x.start-y.start);render()};$('#clear').onclick=()=>{$('#text').value='';selected=-1;render()};
function render(){list.innerHTML=cues.length?'':'<div class="empty">No captions yet. Add one or import an SRT.</div>';cues.forEach((c,i)=>{const d=document.createElement('button');d.className='cue '+(i===selected?'sel':'');d.innerHTML=`<span>${fmt(c.start)} → ${fmt(c.end)}</span><b>${esc(c.text)}</b>`;d.onclick=()=>{selected=i;$('#start').value=c.start;$('#end').value=c.end;$('#text').value=c.text;video.currentTime=c.start;render()};list.append(d)})}
function parseSubs(t){const lines=t.replace(/\r/g,'').split('\n'),out=[];for(let i=0;i<lines.length;){if(!lines[i].trim()){i++;continue}if(/^\d+$/.test(lines[i].trim()))i++;const m=(lines[i]||'').match(/(\d{2}:\d{2}:\d{2}[,.]\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2}[,.]\d{3})/);if(!m){i++;continue}i++;const tx=[];while(i<lines.length&&lines[i].trim()){tx.push(lines[i++])}out.push({start:tm(m[1]),end:tm(m[2]),text:tx.join('\n')})}return out}
function tm(s){const p=s.replace(',','.').split(':').map(Number);return p[0]*3600+p[1]*60+p[2]};function fmt(n){n=Number(n)||0;const h=Math.floor(n/3600),m=Math.floor(n%3600/60),s=(n%60).toFixed(3).padStart(6,'0');return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${s}`};function srtTime(n){return fmt(n).replace('.',',')};function download(txt,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([txt],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#srtOut').onclick=()=>download(cues.map((c,i)=>`${i+1}\n${srtTime(c.start)} --> ${srtTime(c.end)}\n${c.text}\n`).join('\n'),'captions.srt','text/plain');$('#vttOut').onclick=()=>download('WEBVTT\n\n'+cues.map(c=>`${fmt(c.start)} --> ${fmt(c.end)}\n${c.text}\n`).join('\n'),'captions.vtt','text/vtt');render();